"""Authored causal test families. Markdown/CSV/backlog are generated from these records."""


def family(
    identifier,
    name,
    component,
    risk,
    invariant,
    fixture,
    steps,
    expected,
    oracle,
    incident,
    selectors=(),
    *,
    severity="CRITICAL",
    priority="P0",
    group="A",
    cost="bajo",
    kind="integration",
    status="parcial",
    likelihood=3,
    detection=4,
    fp,
    fn,
    effort="2–6 h",
    when="cambio afectado; CI; release; después de incidente",
    real=False,
    windows=False,
    human=False,
    runners=(),
):
    impact = {"CRITICAL": 5, "HIGH": 4, "MEDIUM": 2, "LOW": 1}[severity]
    divisor = {"trivial": 1, "bajo": 2, "medio": 4, "alto": 8}[cost]
    return {
        "TEST_ID": identifier,
        "NOMBRE": name,
        "COMPONENTE": component,
        "RIESGO": risk,
        "SEVERIDAD": severity,
        "INVARIANTE": invariant,
        "PRECONDICIONES": "Entorno aislado; originales preservados; expected independiente. Base B y matrices exactas en QA_CASES.md.",
        "FIXTURE_DATOS": fixture,
        "PASOS_EXACTOS": steps,
        "RESULTADO_ESPERADO": expected,
        "ORACULO": oracle,
        "FALLA": "Cualquier contradicción al resultado esperado, omisión de salida requerida o excepción sin clasificar. Una prueba no ejecutada queda pendiente.",
        "FALSOS_POSITIVOS": fp,
        "FALSOS_NEGATIVOS": fn,
        "AUTOMATIZABLE": "parcialmente" if human or real else "sí",
        "TIPO_IDEAL": kind,
        "COSTO_EJECUCION": cost,
        "VALOR_ESPERADO": "crítico"
        if severity == "CRITICAL"
        else "alto"
        if severity == "HIGH"
        else "medio"
        if severity == "MEDIUM"
        else "bajo",
        "PRIORIDAD": priority,
        "GRUPO": group,
        "CUANDO": when,
        "RESPUESTA_SI_FALLA": incident + " + IR-COMMON (INCIDENT_RESPONSE.md)",
        "ESTADO_COBERTURA": status,
        "SELECTORES": list(selectors),
        "RUNNERS": list(runners),
        "IMPACTO": impact,
        "PROBABILIDAD": likelihood,
        "DIFICULTAD_DETECCION": detection,
        "RIESGO_SCORE": impact * likelihood * detection,
        "VALOR_POR_COSTO": impact * likelihood * detection / divisor,
        "ESFUERZO_IMPLEMENTACION": effort,
        "DATOS_REALES": real,
        "WINDOWS": windows,
        "INTERVENCION_HUMANA": human,
    }


FAMILIES = [
    family(
        "QA-01",
        "Certeza y diferencia confirmada",
        "engine/summary",
        "Falta de respaldo se convierte en discrepancia objetiva",
        "INV-01 INV-10 INV-11",
        "B; A=200,E=100; requisito approval ausente; repetir con issue row y con versión ausente",
        "1. Auditar cada variante por separado. 2. Inspeccionar finding y todos los buckets. 3. Pasar run al checker independiente.",
        "Sin evidencia: REVIEW,E100,Δ100,confirmada0; issue row impide PASS/FAIL; sin versión UNDETERMINABLE/E null. Ningún bucket confirma100.",
        "OR-03 OR-05",
        "IR-03",
        [
            "tests/test_engine.py::test_missing_evidence_does_not_confirm_even_numeric_difference",
            "tests/test_engine.py::test_import_rejects_block_economic_confirmation",
        ],
        fp="Una decisión APPROVED posterior no cambia status del motor.",
        fn="Comprobar sólo finding y no summary/reportes deja escapar dinero confirmado.",
    ),
    family(
        "QA-02",
        "Tolerancia, signo y fronteras",
        "comparison",
        "PASS fuera de tolerancia o FAIL en el límite",
        "INV-02 INV-03",
        "B y N05,N06,N07; E=100/200; límites positivos y negativos",
        "1. Ejecutar A=T exacta y T±0.01 respecto de E. 2. Recalcular T y Δ con Fraction. 3. Revisar PASS/FAIL y neto/brutos.",
        "E100,T0.01,A100.01 PASS;100.02 FAIL+0.02;99.98 FAIL−0.02. E200,rel0.05,A210 PASS;210.01 FAIL10.01.",
        "OR-01 OR-02",
        "IR-01 IR-02 IR-06",
        [
            "tests/test_engine.py::test_tolerance_and_signed_differences",
            "tests/test_qa_infrastructure.py::test_generated_reference_prices",
        ],
        kind="property-based; mutation",
        fp="Confundir Δ calculada de un PASS con confirmada0.",
        fn="Tolerancia relativa, negativo o igualdad exacta no ejercitados.",
    ),
    family(
        "QA-03",
        "Referencia de precio independiente",
        "rules",
        "Fórmula incorrecta coincide con golden generado por el mismo motor",
        "INV-03 INV-14 INV-15",
        "N08,N09; casos generados unit/min/percent; anclas31.5 y42",
        "1. Comprobar anclas de referencia. 2. Generar q/tarifa/mínimo/factor. 3. Comparar E con referencia racional sin importar helpers productivos.",
        "q10×2,min30,+5%→31.5; q20→42. Igual E y A no produce FAIL; cambiar A no cambia E.",
        "OR-01 OR-02",
        "IR-06",
        [
            "tests/test_qa_infrastructure.py::test_reference_manual_anchors",
            "tests/test_qa_infrastructure.py::test_generated_reference_prices",
        ],
        kind="property-based; differential",
        status="nuevo",
        fp="Referencia fuera de su subconjunto no es fallo del motor.",
        fn="Ambos calculan bien pero contrato mal representado; validar OR-01.",
    ),
    family(
        "QA-04",
        "Dominio numérico y tipos estrictos",
        "models/canonical",
        "Coerción, no finito o desborde se acepta como dinero",
        "INV-14 INV-27",
        "N17..N20; float0.1,bool1,NaN,37 dígitos,13 decimales; agregar dos inputs36dígitos",
        "1. Validar cada input. 2. Auditar suma de inputs válidos grandes. 3. Verificar rechazo antes de conclusión o suma exacta.",
        "Inputs inválidos rechazados; 36nueves+1 suma37 dígitos permitida. No coerción bool→decimal ni 1→boolean.",
        "OR-01 OR-03",
        "IR-06",
        [
            "tests/test_engine.py::test_float_prohibited",
            "tests/test_engine.py::test_invalid_money",
            "tests/test_adversarial.py::test_aggregate_amount_can_exceed_individual_input_digit_bound",
            "tests/test_adversarial.py::test_no_boolean_coercion",
        ],
        kind="unit; property-based",
        fp="Aplicar límites de input a agregados internos legítimos.",
        fn="Sólo validar Value y omitir Charge/importer.",
    ),
    family(
        "QA-05",
        "Redondeo, escala y orden",
        "rules/currency_round",
        "Cambio de centavos por modo u orden implícito",
        "INV-15 INV-27",
        "N11..N16; 0.005+0.005; valores negativos; escalas0,2,3,8",
        "1. Ejecutar cada fila manual. 2. Diferenciar round final de dos round explícitos. 3. Comprobar escala/modo/input en trace.",
        "Final0.01; por componente0.02; HALF_EVEN2.345→2.34,2.355→2.36. HALF_DOWN rechazado por configuración.",
        "OR-01 OR-02",
        "IR-06",
        [
            "tests/test_qa_infrastructure.py::test_reference_manual_anchors",
            "tests/test_qa_infrastructure.py::test_generated_reference_prices",
        ],
        kind="property-based; mutation",
        fp="Cambiar expresión contractual es cambio esperado, no invariancia.",
        fn="Sólo positivos/escala2 no detecta truncamiento de créditos.",
    ),
    family(
        "QA-06",
        "División y contexto ambiental",
        "rules/Decimal",
        "Contexto global o precisión cambia resultado sin permiso",
        "INV-14 INV-19",
        "N21..N23; prec global6; numeradores/denominadores negativos; divisor0",
        "1. Comparar división con Decimal alta precisión y casos manuales. 2. Cambiar/restaurar contexto externo. 3. Probar precisión insuficiente.",
        "1/3→0.33;−1/8 HALF_EVEN→−0.12; divisor0/desborde→UNDETERMINABLE/0confirmado. Contexto ajeno no altera audit.",
        "OR-01 OR-08",
        "IR-06",
        [
            "tests/test_engine.py::test_property_division_matches_high_precision",
            "tests/test_engine.py::test_global_decimal_context_does_not_affect_results",
            "tests/test_adversarial.py::test_inexact_comparison_becomes_undeterminable",
        ],
        kind="property-based",
        fp="Referencia Decimal con precisión insuficiente introduce doble redondeo.",
        fn="Rango actual de enteros pequeños no cubre todo exponente válido.",
    ),
    family(
        "QA-07",
        "Unidades y monedas separadas",
        "models/rules/summary",
        "Kg, gramos o monedas se suman como equivalentes",
        "INV-06 INV-13",
        "B+segundo cargoUSD; N24,N25; unidad final vacía o kg",
        "1. Auditar moneda discordante. 2. Introducir g frente a kg sin factor. 3. Añadir factor explícito y acuerdoUSD independiente.",
        "Discordancia→UNDETERMINABLE; sin factor no conversión; 1000g×0.001kg/g×2ARS/kg=2ARS; buckets separados.",
        "OR-01 OR-03",
        "IR-06",
        [
            "tests/test_engine.py::test_currencies_never_summed_or_converted",
            "tests/test_engine.py::test_missing_attribute_and_unit_mismatch",
            "tests/test_engine.py::test_rules_need_currency_units",
        ],
        kind="unit; metamorphic",
        fp="No imponer dos decimales por código ISO.",
        fn="Revisar core pero permitir suma multimoneda en UI.",
    ),
    family(
        "QA-08",
        "Números desde originales",
        "CSV/XLSX importer",
        "Cambio silencioso de magnitud o precisión antes del motor",
        "INV-14 INV-22",
        "XLSX literal1000000000000000.01 y1e999999; CSV1.234,56 y1.23,45; corpus exacto",
        "1. Preservar bytes. 2. Importar con mapping confirmado. 3. Comparar value y provenance.raw con literal independiente.",
        "XLSX preserva fracción; exponente extremo rechaza fila; CSV argentino1234.56; agrupador inválido rechaza, no corrige silenciosamente.",
        "OR-04",
        "IR-07",
        [
            "tests/test_importing.py::test_xlsx_preserves_original_decimal_literal_without_binary_float_loss",
            "tests/test_importing.py::test_xlsx_unbounded_exponent_is_rejected_before_decimal_expansion",
            "tests/test_importing.py::test_argentine_decimal",
            "tests/test_importing.py::test_unsafe_numeric_strings_rejected",
        ],
        kind="fuzz; property-based",
        fp="Un string XLSX respeta locale; no tratarlo igual que celda numérica.",
        fn="Leer expected mediante openpyxl repite el float defectuoso.",
    ),
    family(
        "QA-09",
        "Identidad y normalización declarada",
        "mapping/models",
        "Ceros o caracteres alterados unen entidades distintas",
        "INV-09 INV-22",
        "ref texto00001; numérico1 con máscara00000; fraccional99999999999999.001; Unicode y espacios",
        "1. Importar referencia textual. 2. Repetir numeric_text reject/formatted. 3. Verificar reglas de strip y concepto desconocido.",
        "00001 se conserva; numérico requiere política; fraccional rechaza aunque float parezca entero; concepto desconocido queda external:valor.",
        "OR-04 OR-05",
        "IR-04 IR-07",
        [
            "tests/test_importing.py::test_xlsx_numeric_id_requires_explicit_policy",
            "tests/test_importing.py::test_original_fractional_numeric_identifier_cannot_become_integer_after_float_rounding",
            "tests/test_importing.py::test_unknown_concept_not_canonicalized_by_accident",
        ],
        fp="Strip externo está declarado en modelos; no prometer byte equality del valor normalizado.",
        fn="Alias/Unicode normalizado fuera del mapping puede colisionar en un cliente.",
    ),
    family(
        "QA-10",
        "Estructura CSV y conservación de filas",
        "CSV importer",
        "Fila o columna se desplaza u omite sin rastro",
        "INV-12 INV-22",
        "Quotes multilínea, BOM, cp1252, header duplicado/vacío, fila con columna extra, reordered columns",
        "1. Importar corpus con líneas físicas anotadas. 2. Comparar aceptadas/rechazadas y raw. 3. Permutar columnas/mapping.",
        "Referencia multilínea mantiene siguiente registro en línea4; mapeada repetida/ausente error; valor extra rechaza; economía invariante al reordenar.",
        "OR-04 OR-08",
        "IR-07 IR-11",
        [
            "tests/test_adversarial.py::test_csv_multiline_provenance_uses_actual_line",
            "tests/test_importing.py::test_ambiguous_or_missing_headers_fail_file",
            "tests/test_importing.py::test_reordered_columns_same_normalized_records",
            "tests/test_adversarial.py::test_oversized_unmapped_cells_not_silently_shifted",
        ],
        kind="fuzz; metamorphic",
        fp="Blank lines/headers no son cargos; definir población relevante.",
        fn="Control sólo de cantidad deja desplazamiento con misma cantidad.",
    ),
    family(
        "QA-11",
        "Semántica de libro Excel",
        "XLSX importer",
        "Fórmula, ocultamiento o merge cambia alcance percibido",
        "INV-12 INV-14 INV-22",
        "Libro2hojas/hiddenrows/merged/date styles/formula con cache; ver corpus en QA_CASES",
        "1. Especificar sheet. 2. Importar con columnas requeridas vacías/merged. 3. Añadir fórmula cacheada y fila oculta. 4. Cotejar alcance declarado.",
        "Varias hojas sin selección error; fórmula mapeada rechazada; sin fill-forward. Hoja o datos ocultos bloquean la importación hasta hacerlos visibles y revisar el alcance.",
        "OR-04",
        "IR-07 IR-15",
        [
            "tests/test_importing.py::test_multisheet_requires_selection",
            "tests/test_importing.py::test_xlsx_formula_never_evaluated_or_taken_as_cache",
            "tests/test_importing.py::test_original_numeric_tokens_follow_sparse_sheet_coordinates",
            "tests/test_importing.py::test_xlsx_hidden_business_data_blocks_import_until_made_visible",
            "tests/test_importing.py::test_xlsx_hidden_selected_sheet_blocks_import",
        ],
        cost="medio",
        kind="fuzz; manual",
        human=True,
        fp="Fila oculta puede ser legítima; no descartarla por defecto.",
        fn="Los casos de ocultamiento probados no cubren todos los productores, estilos, merges ni caches reales.",
    ),
    family(
        "QA-12",
        "XLS legacy y cache explícito",
        "xlrd/importer",
        "Fórmula guardada o binario impreciso parece hecho verificado",
        "INV-14 INV-22",
        "XLS BIFF con valores/fórmulas guardadas, codepage, epochs; montos alta precisión",
        "1. Importar sin allow_xls_cached_values. 2. Habilitar y revisar warning. 3. Cotejar pares de celdas fuera de xlrd.",
        "Sin aceptación error; con aceptación warning persistente. No declarar recuperación de precisión perdida ni garantía de recalculado.",
        "OR-04",
        "IR-07",
        ["tests/test_importing.py::test_xls_requires_explicit_cached_value_acceptance"],
        severity="HIGH",
        priority="P1",
        cost="medio",
        human=True,
        kind="fuzz; manual",
        fp="Warning esperado no es fallo; su ausencia sí.",
        fn="XLS generado por xlwt no cubre todos los productores reales.",
    ),
    family(
        "QA-13",
        "Límites de importación y corrupción",
        "file parser/API",
        "Archivo agota recursos o produce un lote parcial silencioso",
        "INV-12 INV-25",
        "Archivo25MiB+, ZIP declarado150MiB+,250columnas+,200001filas+,bytes truncados",
        "1. Crear cabeceras/payloads pequeños que activen límites. 2. Ejecutar en subprocess con timeout/RSS. 3. Comprobar clasificación y ausencia de corrida parcial.",
        "ImportErrorDetail/422 útil antes de agotar recursos; ningún resultado económico confirmado para importación abortada.",
        "OR-09 OR-10",
        "IR-07 IR-14",
        ["tests/test_importing.py::test_malformed_xlsx_fuzz_is_bounded_and_classified"],
        severity="HIGH",
        priority="P1",
        group="B",
        cost="alto",
        kind="fuzz; security",
        effort="1–2 días",
        fp="Timeout del equipo saturado requiere repetir aislado una vez.",
        fn="Bytes aleatorios cortos no atraviesan parser profundo; tamaño declarado no prueba expansión real.",
    ),
    family(
        "QA-14",
        "Importación incompleta y alcance documental",
        "import/core/operator",
        "Total aceptado se confunde con total factura",
        "INV-11 INV-12 INV-29",
        "B con fila importe inválida; documento externo total200 mientras aceptado100; archivo faltante",
        "1. Contar filas de negocio. 2. Conciliar accepted/rejected/omitted. 3. Auditar issue row. 4. Comparar contra total externo y etiqueta UI.",
        "Rechazo impide certeza del lote. Archivo nunca aportado no se detecta por core: control externo obligatorio y déficit visible.",
        "OR-03 OR-04 OR-01",
        "IR-02 IR-07",
        [
            "tests/test_engine.py::test_import_rejects_block_economic_confirmation",
            "tests/test_integration.py::test_invalid_fixture_rejects_visible_rows",
            "tests/test_external_control.py::test_external_inventory_count_and_total_are_independent_blockers",
            "tests/test_external_control.py::test_external_control_cli_exit_codes_and_hash_integrity",
        ],
        runners=[".venv/bin/python scripts/qa.py external-control ARCHIVO_AUDIT_JSON CONTROL_EXTERNO_JSON"],
        human=True,
        fp="Subtotal/cabecera no es fila económica duplicada.",
        fn="El comparador sólo detecta omisiones incluidas en un inventario externo independiente; no puede demostrar que ese inventario sea verdadero/completo ni reemplaza la validación humana.",
    ),
    family(
        "QA-15",
        "Procedencia verificable",
        "import/trace/storage",
        "Dato usado no puede reconstruirse desde original",
        "INV-22",
        "CSVmultilínea, XLSXfila3, constante mapping; original con un byte cambiado",
        "1. Del finding seguir trace.field→registro→SourceRef. 2. Verificar SHA y localizar celda. 3. Contrastar raw→transform→value, incluidas constantes.",
        "Documento/hoja/fila/columna/raw correctos y mapping congelado; archivo alterado se rechaza; constante respaldada por configuración.",
        "OR-04 OR-06",
        "IR-11",
        [
            "tests/test_importing.py::test_csv_argentine_numbers_zeroes_and_provenance",
            "tests/test_storage_reporting.py::test_tampered_source_detected",
        ],
        human=True,
        fp="Dataset manual puede carecer de provenance por contrato actual; exigirla en importados.",
        fn="Hash correcto de archivo no demuestra referencia a la celda correcta.",
    ),
    family(
        "QA-16",
        "Selección única de vigencia",
        "engine.select_version",
        "Tarifa equivocada por frontera/gap/overlap",
        "INV-07 INV-08 INV-16",
        "QA_CASES calendario V1=100/V2=120, fin06-30/inicio07-01; versiones invertidas",
        "1. Evaluar comienzo/fin/día siguiente. 2. Crear overlap/gap. 3. Invertir orden de versiones. 4. Consolidar fechas de ambos lados.",
        "Extremos inclusivos; cero/dos versiones o grupo mixto→UNDETERMINABLE; no elegir primera ni prorratear.",
        "OR-05",
        "IR-05",
        [
            "tests/test_engine.py::test_version_boundaries",
            "tests/test_engine.py::test_overlapping_versions_never_pick_first",
            "tests/test_engine.py::test_group_mixed_version_is_undeterminable",
        ],
        kind="property-based; mutation",
        fp="Día dentro de versión puede ser FAIL por importe, no por fecha.",
        fn="Dos versiones con mismo precio ocultan selector equivocado.",
    ),
    family(
        "QA-17",
        "Fecha civil y seriales de Excel",
        "import/date types",
        "Fecha cambia por locale/época/hora y selecciona otra tarifa",
        "INV-08 INV-22",
        "Matriz temporal completa:03/04 ambiguo, leap2024/2026, serial60, epochs1900/1904, midnight/offset",
        "1. Importar cada par fuente→fecha esperada. 2. Repetir con TZs distintas. 3. Comparar versión seleccionada con calendario manual.",
        "Ambigua/invalid/hora/zona→rechazo; medianoche ingenua admitida. Serial ficticio60 del calendario1900 se rechaza; serial60 de1904 es01/03/1904.",
        "OR-04 OR-05",
        "IR-05 IR-07",
        [
            "tests/test_importing.py::test_ambiguous_date_is_rejected",
            "tests/test_importing.py::test_excel_fictitious_leap_day_never_aliases_real_date",
            "tests/test_importing.py::test_timestamps_are_not_silently_truncated",
            "tests/test_engine.py::test_alternate_date_field",
        ],
        kind="fuzz; property-based",
        cost="medio",
        fp="Cambiar date_field contractual legítimamente cambia tarifa.",
        fn="Comparar sólo date final pierde serial/epoch original.",
    ),
    family(
        "QA-18",
        "Reglas/condiciones y AST acotado",
        "models/rules",
        "Default inventado o condición desconocida se trata falsa",
        "INV-07 INV-13",
        "B con0/2reglas aplicables, condición ausente, if lazy, op desconocida, profundidad31",
        "1. Validar AST inválidos. 2. Evaluar datos faltantes. 3. Probar rama no elegida con división0. 4. Repetir reglas reordenadas.",
        "AST inválido rechaza;0/2reglas→UNDETERMINABLE; if no evalúa rama no elegida; condición faltante no es false.",
        "OR-01 OR-05",
        "IR-03 IR-06",
        [
            "tests/test_engine.py::test_condition_missing_is_not_false",
            "tests/test_engine.py::test_condition_branch_is_lazy",
            "tests/test_engine.py::test_overlapping_rules_are_undeterminable",
            "tests/test_adversarial.py::test_bounded_expression_depth_rejects_nested_attack",
        ],
        fp="and/or actualmente evalúan todos los operandos; sólo if promete lazy.",
        fn="Test AST parseado no prueba aridad/semántica de cada operador.",
    ),
    family(
        "QA-19",
        "Lookup/bandas sin desempate arbitrario",
        "rules/tables",
        "Primer precio coincidente reemplaza ambigüedad real",
        "INV-07 INV-13 INV-16",
        "N10, tabla con clave repetida/mismo precio, gap/overlap, unidadesdiscordantes",
        "1. Evaluar ambos lados y límite exacto. 2. Repetir filas. 3. Invertir tabla. 4. Intercalar versión con tabla homónima diferente.",
        "Bandas[lower,upper); exactamente1coincidencia. Cero/dos incluso mismo importe→UNDETERMINABLE; caché separada por versión/acuerdo.",
        "OR-05",
        "IR-05 IR-06",
        [
            "tests/test_adversarial.py::test_band_overlap_and_gap_never_select_arbitrarily",
            "tests/test_adversarial.py::test_duplicate_lookup_rows_even_same_price_are_ambiguous",
        ],
        kind="property-based; mutation",
        fp="Orden textual de tabla puede cambiar hash, economía no.",
        fn="Mismo valor en tablas distintas oculta contaminación de caché.",
    ),
    family(
        "QA-20",
        "Claves, aliases y vínculos explícitos",
        "matching",
        "Entidad equivocada por resolución implícita",
        "INV-09 INV-26",
        "Taxonomía matching1→1/compuesto/alias; clave vacía; explícito inválido/contradictorio",
        "1. Dibujar grafo manual. 2. Aplicar alias sólo al cargo. 3. Vaciar clave. 4. Añadir link inválido y verificar sin fallback.",
        "Match exacto declarado; vacíos no empatan; link ausente/repetido/carrier ajeno→UNDETERMINABLE. Contradicción link/claves requiere control adicional pendiente.",
        "OR-05",
        "IR-04",
        [
            "tests/test_engine.py::test_composite_keys_and_directional_alias",
            "tests/test_engine.py::test_invalid_explicit_link_never_falls_back",
            "tests/test_adversarial.py::test_empty_keys_never_join_to_empty_keys",
        ],
        fp="Precedencia explicit sobre keys es contrato actual; no confundirla con detección de intención errónea.",
        fn="Explicito válido estructuralmente puede apuntar a operación equivocada.",
    ),
    family(
        "QA-21",
        "Ambigüedad propagada a grupos parciales",
        "matching/aggregation",
        "FAIL falso por comparar sólo fracción asignada",
        "INV-09 INV-04",
        "S1/S2 misma referencia; C1=40 explícitoS1,C2=60 ambiguo; E100",
        "1. Auditar en ambos órdenes. 2. Inspeccionar los dos findings. 3. Resolver C2 explícitamente y volver a auditar nueva copia.",
        "Antes: ambos REVIEW/confirmada0; después, si C1+C2→S1, grupoA100,E100 PASS. Ningún cargo se pierde.",
        "OR-03 OR-05",
        "IR-04 IR-03",
        [
            "tests/test_adversarial.py::test_ambiguous_allocation_also_blocks_related_partial_group",
            "tests/test_engine.py::test_matching_ambiguity_is_review",
        ],
        fp="No exigir un único finding antes/después; cambia agrupación.",
        fn="Revisar sólo cargo ambiguo deja FAIL parcial en el otro.",
    ),
    family(
        "QA-22",
        "Consolidado y cargos por componentes",
        "matching/rules",
        "Expected repetido en1→N o N→1 incompleto",
        "INV-04 INV-05 INV-09",
        "S1peso10,S2peso20;group lote;tarifa2; C40+C20; duplicate_fields vacío",
        "1. Auditar sum×2. 2. Dividir/reunir líneas actual. 3. Cambiar sum por attr sobre pesos distintos. 4. Comparar scopes, no IDs hash.",
        "UnE60,A60 PASS; split no repiteE. attr de pesos distintos→UNDETERMINABLE; no prorrateo automático.",
        "OR-02 OR-03 OR-08",
        "IR-04 IR-06",
        [
            "tests/test_engine.py::test_group_sum_and_one_expected_charge",
            "tests/test_engine.py::test_multiple_lines_aggregate_without_inventing_duplicates",
        ],
        kind="property-based; metamorphic",
        fp="Mínimo por envío no es aditivo; no aplicar MT12 fuera de sus precondiciones.",
        fn="N→M solapado no se cubre con N→1.",
    ),
    family(
        "QA-23",
        "Asignaciones superpuestas y servicios parciales",
        "allocation",
        "Misma obligación se confirma dos veces",
        "INV-09 INV-05",
        "C1→S1,S2;C2→S2,S3 mismo concepto; servicio tramo parcial sin política",
        "1. Construir grafo con intersecciónS2. 2. Auditar. 3. Verificar grupo relacionado no confirma ni reparte. 4. Confirmar límite contractual con operador.",
        "Grupos superpuestos REVIEW; no multiplicar expected confirmado. Servicio parcial no representado se bloquea hasta definir regla.",
        "OR-05",
        "IR-04 IR-15",
        ["tests/test_engine.py::test_overlap_allocations_are_review"],
        human=True,
        fp="Conceptos independientes sobre mismo S no son el mismo scope económico.",
        fn="Solapamiento a través de acuerdos distintos requiere revisión contractual.",
    ),
    family(
        "QA-24",
        "Duplicados candidatos y remito legítimo",
        "matching",
        "Deduplicar importe válido o confirmar sospecha",
        "INV-17 INV-04",
        "Dos cargos refigual/conceptigual/importeigual; clavesduplicado activas/inactivas; conceptos distintos",
        "1. Auditar con duplicate_fields. 2. Desactivar sólo esa política. 3. Separar conceptos y verificar conservación.",
        "Candidatos→REVIEW, no eliminación ni ahorro; sin política líneas agregadas; distinto concepto no es duplicado por referencia sola.",
        "OR-03 OR-05",
        "IR-03 IR-04",
        [
            "tests/test_engine.py::test_configured_duplicate_is_candidate_only",
            "tests/test_engine.py::test_same_remittance_different_concepts_is_not_duplicate",
        ],
        fp="Mismo remito legítimo puede requerir claves más específicas.",
        fn="No configurar duplicate_fields no demuestra ausencia de duplicados reales.",
    ),
    family(
        "QA-25",
        "Evidencia por ámbito y adición selectiva",
        "evidence",
        "Respaldo ajeno o insuficiente certifica cargo",
        "INV-10 INV-20",
        "DosS,each_shipment/each_charge/group,any_of approval/POD,document_required; evidencia ajena",
        "1. Retirar un respaldo por ámbito. 2. Agregar sólo el faltante. 3. Comparar grupos no relacionados y run original. 4. Retirar documento obligatorio.",
        "Faltante→REVIEW; evidencia suficiente sólo resuelve scope pertinente; nueva corrida puede PASS o FAIL según Δ, historia intacta.",
        "OR-05 OR-08",
        "IR-03 IR-11",
        [
            "tests/test_engine.py::test_evidence_any_of_and_per_operation",
            "tests/test_engine.py::test_unrelated_evidence_cannot_support_charge",
        ],
        kind="property-based; metamorphic",
        fp="Añadir respaldo puede convertir REVIEW en FAIL legítimo; no exigir PASS.",
        fn="Sólo kind sin revisar asociaciones/document_hash es falso respaldo.",
    ),
    family(
        "QA-26",
        "Cobertura explícita de cargos ausentes",
        "coverage",
        "Inventar deuda o duplicar hallazgo de cobertura",
        "INV-18 INV-04",
        "B sin cargos;rule.expected true; coverage vacío/explícito; versión ausente; carrier incorrecto",
        "1. Comparar sin/con coverage. 2. Probar when=false. 3. Agregar cargo ya indeterminado. 4. Validar scope inválido.",
        "Sin scope no inventar; scope correcto→REVIEW A0 sin confirmada; whenfalse omite expectativa; no duplica cargo sin versión; scope inválido rechaza.",
        "OR-03 OR-05",
        "IR-03 IR-04",
        [
            "tests/test_engine.py::test_missing_expected_charge_requires_explicit_scope_and_is_review",
            "tests/test_adversarial.py::test_missing_coverage_must_not_duplicate_existing_undetermined_charge",
            "tests/test_adversarial.py::test_coverage_cannot_silently_drop_wrong_carrier",
        ],
        fp="Hallazgo sin cargo aumenta findings pero no charge_counts.",
        fn="Creer que cobertura detecta documento faltante no aportado.",
    ),
    family(
        "QA-27",
        "Conservación total por ID y moneda",
        "aggregate/all states",
        "Omisión o doble conteo queda oculto por neto",
        "INV-03 INV-04 INV-05 INV-06",
        "B extendido PASS/FAIL±/REVIEW/UNDETERMINABLE; cargo unmatched;0/negativos; dosmonedas",
        "1. Checker recompone Counter de charge_ids y sumas desde C. 2. Comparar todos los buckets/counts. 3. Mutar salida duplicando/quitando cargo.",
        "Cada C exactamente1vez; bruto por moneda preservado; +50 y−75 separados y neto−25. Checker rechaza salida manipulada.",
        "OR-03",
        "IR-01 IR-02 IR-06",
        ["tests/test_qa_infrastructure.py::test_checker_rejects_economic_corruption"],
        kind="property-based; mutation",
        status="nuevo",
        fp="Créditos invalidan desigualdad determinable≤actual; usar identidades firmadas.",
        fn="Totales coincidentes pueden ocultar omisión y duplicación compensadas: contar IDs.",
    ),
    family(
        "QA-28",
        "Determinismo y transformaciones",
        "core/canonical/import",
        "Orden/nombre/ambiente modifica dinero",
        "INV-19 INV-21",
        "MT01..MT20 con nivel de igualdad declarado; A/B/A; cambio future/filename/columns",
        "1. Guardar baseline completo. 2. Aplicar una transformación. 3. Comparar resultado o economic_projection según tabla. 4. Comprobar fuente hash cambia cuando bytes cambian.",
        "Reordenamiento normalizado completo igual; renombre/columna economía igual aunque snapshot hash cambie; cambio futuro no muta run guardado.",
        "OR-08",
        "IR-09",
        [
            "tests/test_engine.py::test_property_arbitrary_row_permutation",
            "tests/test_engine.py::test_semantic_hash_ignores_incidental_label",
            "tests/test_qa_infrastructure.py::test_generated_uncertainty_and_metamorphism",
        ],
        kind="metamorphic; property-based",
        fp="Exigir semantic_hash igual al agregar versión futura produce falso fallo.",
        fn="Dos errores idénticos satisfacen relación; combinar OR02/03.",
    ),
    family(
        "QA-29",
        "Aislamiento entre clientes y catálogos",
        "configuration/storage/cache",
        "Acuerdo o datoB influyeA sin alarma",
        "INV-26",
        "DosDB, mismosS/C/A/tableIDs; Aprecio100,B900; import originales distintos",
        "1. EjecutarA/B/A en proceso. 2. Reabrir DBs y comparar A. 3. Intentar selección de config ajena en UI y revisar operación.",
        "A idéntico, fuentes/configs separadas por DB. Catálogo global dentro mismaDB no es aislamiento multiempresa; no habilitarlo como tal.",
        "OR-05 OR-06 OR-08",
        "IR-13",
        ["tests/test_backlog_p0_p1.py::test_qa29_client_catalog_and_storage_isolation"],
        status="parcial",
        cost="medio",
        human=True,
        fp="Diferencia de label/input_hash no prueba contaminación económica.",
        fn="DatosconIDsdistintos nunca ejercitan colisión/caché compartida.",
    ),
    family(
        "QA-30",
        "Decisiones humanas y cadena",
        "storage/UI",
        "Resolución borra finding o decisión previa",
        "INV-20 INV-24",
        "RunB;APPROVED→REJECTED; dos escritores; finding/evidence ajenos",
        "1. Guardar hash de resultado. 2. Añadir decisiones en orden/concurrentes. 3. Verificar chain/resultado. 4. Intentar referencias ajenas.",
        "Resultado original idéntico; decisiones append-only ordenadas/hash enlazado; referencias inexistentes rechazadas.",
        "OR-06",
        "IR-10",
        [
            "tests/test_storage_reporting.py::test_human_decision_never_rewrites_finding",
            "tests/test_storage_reporting.py::test_decision_chain_serializes_concurrent_writers",
            "tests/test_storage_reporting.py::test_no_unknown_decision_or_evidence",
        ],
        fp="Hash de paquete cambia al añadir decisión legítima.",
        fn="Cadena local no detecta truncamiento de sufijo sin ancla externa.",
    ),
    family(
        "QA-31",
        "Integridad histórica y mutación",
        "SQLite/snapshot",
        "Corrida alterada sigue pareciendo confiable",
        "INV-20 INV-28",
        "CopiaDB; UPDATE/DELETE normales y bypass de trigger controlado en copia; cambio deV2",
        "1. Guardar ancla externa. 2. Intentar mutación. 3. Comparar load y list_runs ante byte alterado. 4. Abrir original intacto.",
        "Writes históricos bloqueados; load detecta hashes; configuración futura no cambia run. list_runs no verifica integridad: deuda visible, no oráculo.",
        "OR-06",
        "IR-10",
        [
            "tests/test_storage_reporting.py::test_db_update_delete_blocked",
            "tests/test_storage_reporting.py::test_tampered_result_detected_after_trigger_bypass",
            "tests/test_storage_reporting.py::test_changed_agreement_preserves_history",
        ],
        fp="Metadata/created_at fuera del hash actual no está autenticada.",
        fn="Rehash malicioso total o truncamiento puede pasar sin copia externa.",
    ),
    family(
        "QA-32",
        "Replay y cambio de artefacto",
        "storage/replay",
        "Resultado nuevo se presenta como reproducción histórica",
        "INV-21 INV-19",
        "RunB; snapshot/ancla; fuente altered; artifact distinto; proceso abierto con código cambiado",
        "1. Replay original. 2. Alterar fuente/snapshot en copia. 3. Cambiar artifact o código cargado. 4. Confirmar que no reescribe resultado.",
        "Mismo artefacto: resultado exacto. Integridad fallida, artefacto distinto o proceso desactualizado bloquean replay. Reimportar es otra operación.",
        "OR-06 OR-08",
        "IR-09 IR-10",
        [
            "tests/test_storage_reporting.py::test_save_replay_and_idempotency",
            "tests/test_storage_reporting.py::test_engine_artifact_change_blocks_replay",
            "tests/test_storage_reporting.py::test_source_update_requires_process_restart",
        ],
        fp="Rechazar otro artefacto no demuestra falta de determinismo.",
        fn="Replay perfecto perpetúa error de importer previo.",
    ),
    family(
        "QA-33",
        "Proveniencia de ejecutables y alcance",
        "metadata/incident tooling",
        "No localizar históricos afectados por importer/reportero",
        "INV-21 INV-28 INV-30",
        "Base histórica sin importer_hash ni client_id; operador configurado pero no ejecutado; corrida dañada.",
        "1. Ejecutar impact con --feature const y --importer-hash distinto. 2. Conservar desconocidos como candidatos. 3. Contrastar inventario manual. 4. Comparar bytes de la base antes/después.",
        "Unknown no se excluye; config y trace consultadas; cliente declarado externamente; no escribir schema/triggers ni inventar huellas pasadas.",
        "OR-05 OR-06",
        "IR-09 IR-13",
        ["tests/test_qa_infrastructure.py::test_impact_is_read_only_and_retains_unknowns"],
        status="nuevo",
        fp="Candidato configurado puede no haber ejecutado feature: conservador, no afirmación de daño.",
        fn="Filtrar sólo trace pierde errores previos a calcular.",
    ),
    family(
        "QA-34",
        "Backup, restore y reapertura",
        "SQLite/operations",
        "Backup existe pero no recupera historia/fuentes",
        "INV-25 INV-28",
        "Base con dos corridas, decisiones y fuentes; destino nuevo para backup y otro ya existente.",
        "1. Crear backup con la API. 2. Restaurar en otra ruta. 3. Verificar inventario, hashes, decisiones, fuentes y replay con el artefacto original. 4. Intentar sobrescribir el destino existente.",
        "Copia consistente y mismas corridas; overwrite rechazado; original intacto. Copia fuera del equipo exige operación real.",
        "OR-06 OR-10",
        "IR-12",
        ["tests/test_storage_reporting.py::test_migration_reopening_and_consistent_backup"],
        cost="medio",
        human=True,
        fp="Ese test se llama migration pero sólo prueba inicialización/reapertura.",
        fn="Backup sobre mismo disco no cubre pérdida del equipo.",
    ),
    family(
        "QA-35",
        "Crash, rollback y concurrencia",
        "SQLite/exports",
        "Transacción parcial o dos procesos duplican/perdieron historia",
        "INV-25 INV-04",
        "Subproceso sobre copia de base; fallo antes/después de INSERT y commit; dos corridas simultáneas; disco lleno simulado.",
        "1. Inyectar fallo en frontera transaccional. 2. Reabrir copia. 3. Inventariar completos/ausentes y fuentes huérfanas. 4. Validar no corrida parcial visible.",
        "Run completo o ausente, cadena íntegra; busy error recuperable. Fuentes huérfanas pueden existir y no son pérdida histórica; export incompleto no se presenta como completo.",
        "OR-06 OR-10",
        "IR-12",
        ["tests/test_storage_reporting.py::test_decision_chain_serializes_concurrent_writers"],
        cost="alto",
        group="B",
        kind="integration; fault injection",
        effort="1–3 días",
        fp="Proceso terminado no prueba que un commit previo deba desaparecer.",
        fn="Thread test de decisiones no cubre kill de proceso o full disk.",
    ),
    family(
        "QA-36",
        "Schema y migración recuperable",
        "SQLite/version upgrade",
        "Migración interpreta datos previos con semántica nueva",
        "INV-20 INV-25",
        "Base vacía, schema v1, schema futuro v2, v0 no vacío y schema incompleto; futura migración interrumpida.",
        "1. Abrir copias de cada estado. 2. Para una futura migración: preservar backup con hash externo, interrumpir antes/después de cada DDL y restaurar/reintentar. 3. Comparar corridas históricas y originales.",
        "Vacía inicializa schema 1; versión futura se rechaza; v1 reabre sin cambios. v0 no vacío o incompleto requiere validación pendiente. No se certifica una migración real.",
        "OR-06",
        "IR-10 IR-12",
        [
            "tests/test_storage_reporting.py::test_newer_database_schema_is_not_opened",
            "tests/test_storage_reporting.py::test_migration_reopening_and_consistent_backup",
        ],
        group="B",
        cost="alto",
        when="migración; release con cambio de schema",
        effort="1–3 días",
        fp="No inventar downgrade de schema futuro.",
        fn="Una prueba de reopen no cubre atomicidad del DDL.",
    ),
    family(
        "QA-37",
        "Reconciliación entre representaciones",
        "JSON/SQLite/API/XLSX/HTML/UI",
        "Salida cambia estado, importe o identidad",
        "INV-23 INV-03",
        "Corrida ficticia con cuatro estados y dos monedas; ocho hojas XLSX; JSON y HTML exportados; respuesta API y observación DOM.",
        "1. Verificar integridad e invariantes. 2. Leer salidas con lectores independientes. 3. Comparar filas, monedas, estados, importes y resúmenes. 4. Alterar cada salida por separado y exigir detección.",
        "Campos materiales exactos; filas completas y sin fórmulas. API y DOM sólo se cubren al aportar capturas independientes. Un canal ausente queda pendiente.",
        "OR-03 OR-07",
        "IR-08",
        ["tests/test_qa_infrastructure.py::test_cross_report_reconciliation_and_tamper_detection"],
        status="nuevo",
        cost="medio",
        fp="HTML es resumen: no exigir columna inexistente, sí su contenido declarado.",
        fn="Conciliar salidas iguales no prueba que el core aplicó contrato correcto.",
    ),
    family(
        "QA-38",
        "Límites de reportes y contenido activo",
        "reporting",
        "Truncamiento silencioso o fórmula/HTML se ejecuta",
        "INV-23 INV-25",
        "Texto de 32768 caracteres, límite de filas reducido en test, nota con =HYPERLINK o script, importes de 36 dígitos.",
        "1. Exportar. 2. Revisar tipos y cantidad de celdas. 3. Forzar límite y verificar ZIP sin XLSX, advertencia explícita y JSON completo. 4. Inspeccionar escape del HTML.",
        "No se entrega un XLSX parcial; texto explícito sin fórmulas; JSON íntegro y advertencia de omisión conservada.",
        "OR-07 OR-09",
        "IR-08 IR-14",
        [
            "tests/test_storage_reporting.py::test_workbook_is_real_and_has_exact_money_and_no_formulas",
            "tests/test_storage_reporting.py::test_report_escapes_untrusted_html_and_excel_formula",
            "tests/test_storage_reporting.py::test_excel_long_cell_is_not_silently_truncated",
            "tests/test_storage_reporting.py::test_excel_row_limit_preserves_full_bundle_json",
        ],
        kind="integration; security",
        fp="Texto exacto en Excel no es celda numérica sumable automáticamente.",
        fn="Probar un límite reducido no mide la memoria real para 100000 filas.",
    ),
    family(
        "QA-39",
        "UI conserva semántica visible y estado actual",
        "browser/UI",
        "Filtro/cache/formato muestra otra auditoría o dinero alterado",
        "INV-23 INV-24 INV-29",
        "Dos corridas similares; importe textual 1000000000000000.01; 150 hallazgos; cuatro estados y decisión humana distinta del estado del motor.",
        "1. Capturar DOM de todas las páginas y filtros. 2. Cambiar rápidamente de corrida, abrir detalle y registrar decisión. 3. Comparar valores y etiquetas con la corrida exacta. 4. Probar importes con cero y tres decimales.",
        "Dinero sin conversión a Number/float; paginación y filtros no cambian métricas globales. Estado del motor y decisión separados; solicitudes sólo a loopback.",
        "OR-07 OR-09",
        "IR-08",
        [],
        status="parcial",
        runners=[".venv/bin/python scripts/browser_e2e.py --output-dir output/playwright/qa39-new"],
        cost="medio",
        kind="E2E",
        human=True,
        effort="1–2 días",
        fp="Captura de una página no equivale al lote entero; registrar filtro.",
        fn="Una respuesta exitosa de API no prueba qué leyó el operador.",
    ),
    family(
        "QA-40",
        "Barrera de red local",
        "server/CLI",
        "Página ajena opera sobre datos locales",
        "INV-26 INV-30",
        "Host malicioso, Origin ajeno, token faltante o erróneo, preflight CORS y socket real del servicio.",
        "1. Enviar POST con y sin token y Origin válidos. 2. Verificar bind a 127.0.0.1 en el proceso CLI. 3. Probar lectura desde otro origen en navegador. 4. Inspeccionar efectos en la base.",
        "Host, Origin o token incorrectos se rechazan; CORS sin orígenes ajenos; servicio sólo en loopback. Un rechazo con efectos previos en la base es un fallo.",
        "OR-09",
        "IR-14",
        ["tests/test_integration.py::test_local_api_security_boundary"],
        kind="security; E2E",
        runners=[".venv/bin/python scripts/browser_e2e.py --output-dir output/playwright/qa40-new"],
        fp="Token local no autentica usuarios del mismo equipo.",
        fn="El E2E de Chromium/Linux no prueba firewall ni aislamiento frente a otros usuarios del equipo; falta matriz Windows.",
    ),
    family(
        "QA-41",
        "Rutas, archivos y sobrescritura",
        "upload/export/backup",
        "Lectura/escritura fuera del destino permitido",
        "INV-25 INV-30",
        "Archivo testigo externo; ../../name, ruta absoluta, ruta Windows, enlace simbólico y destino existente.",
        "1. Subir un archivo con nombre hostil. 2. Exportar y crear backup en destinos temporales existentes y enlaces simbólicos. 3. Verificar el testigo y archivos modificados. 4. Usar sólo datos sintéticos.",
        "Uploads identificados por hash; sin lectura ni escritura arbitrarias; sobrescritura rechazada. Verificar política de enlaces simbólicos antes de usar rutas compartidas.",
        "OR-09",
        "IR-14",
        [
            "tests/test_security_paths.py::test_export_rejects_existing_and_redirected_directories",
            "tests/test_security_paths.py::test_foreign_platform_drive_syntax_is_not_a_local_relative_output",
            "tests/test_security_paths.py::test_backup_publishes_only_completed_copy_without_overwrite",
            "tests/test_security_paths.py::test_export_marks_interrupted_or_invalid_package",
            "tests/test_integration.py::test_upload_filename_is_only_a_label_and_never_an_output_path",
        ],
        status="parcial",
        cost="medio",
        kind="security",
        windows=True,
        effort="1–2 días",
        fp="CLI acepta ruta elegida por operador; no confundirla con ruta controlada por upload.",
        fn="La comprobación de enlaces no detiene a otro proceso del mismo usuario que cambie directorios durante la escritura; falta ejecutar la matriz nativa Windows.",
    ),
    family(
        "QA-42",
        "XML/ZIP malicioso acotado",
        "XLSX/bundle",
        "Entidades externas, bomb o entrada ambigua supera defensa",
        "INV-25 INV-30",
        "DTD pequeña con entidad hacia archivo testigo; entradas ZIP repetidas o con ../; tamaños declarados y reales; presupuesto de proceso.",
        "1. Generar un archivo sintético pequeño. 2. Ejecutar en subproceso sin red y con límites. 3. Registrar rechazo, salidas, red y testigo. 4. Verificar expansión efectiva y cabecera.",
        "Sin ejecución de contenido, red ni lectura externa; error recuperable; ninguna corrida económica parcial. Archivos sintéticos y acotados.",
        "OR-09",
        "IR-14",
        [
            "tests/test_importing.py::test_malformed_xlsx_fuzz_is_bounded_and_classified",
            "tests/test_importing.py::test_xlsx_duplicate_or_traversal_entry_is_rejected",
            "tests/test_importing.py::test_xlsx_external_entity_never_becomes_imported_value",
        ],
        cost="medio",
        kind="fuzz; security",
        fp="Rechazo genérico de corrupción es aceptable si no hay efecto y orienta recuperación.",
        fn="DTD y ZIP ambiguo sintéticos no prueban todos los productores XML ni el pico de descompresión real bajo un límite de proceso.",
    ),
    family(
        "QA-43",
        "Errores de API y consistencia de operación",
        "FastAPI",
        "422/500 oculta escritura parcial o resultado diferente a CLI",
        "INV-25 INV-29",
        "Mapping inválido, campo extra, ID ajeno, upload mayor de 32 MiB y misma entrada válida por CLI/API.",
        "1. Registrar inventario de la base. 2. Enviar petición inválida. 3. Comparar fuentes y configuraciones conservadas con corridas creadas. 4. Enviar entrada válida y contrastar con CLI.",
        "Error recuperable sin traceback para el usuario; ninguna corrida parcial; mismo resultado económico por CLI/API; sin datos sensibles expuestos.",
        "OR-03 OR-07",
        "IR-07 IR-08 IR-12",
        [
            "tests/test_integration.py::test_api_configuration_errors_use_recoverable_messages",
            "tests/test_integration.py::test_api_runs_decisions_export_replay",
            "tests/test_integration.py::test_api_import_with_mapping_and_provenance",
        ],
        severity="HIGH",
        priority="P1",
        fp="La vista previa puede conservar una fuente o configuración sin ejecutar la auditoría.",
        fn="Comprobar sólo el código de respuesta ignora el cuerpo y los efectos persistidos.",
    ),
    family(
        "QA-44",
        "Auditoría sin servicios externos",
        "core/CLI/UI",
        "Dependencia remota exfiltra o impide auditar",
        "INV-19 INV-30",
        "Fixtures instalados, conexiones externas bloqueadas y monitor de solicitudes del navegador.",
        "1. Bloquear conexiones externas para core y CLI. 2. Importar, auditar, exportar y reproducir. 3. Navegar la UI y revisar destinos de todas las solicitudes.",
        "Auditoría y exportaciones íntegras sin red; UI sólo en loopback. Evaluar instalación inicial de dependencias por separado.",
        "OR-09",
        "IR-14",
        ["tests/test_integration.py::test_fully_offline_core"],
        severity="HIGH",
        priority="P1",
        kind="integration; E2E",
        fp="Instalar sin red requiere paquetes previos; esto no demuestra dependencia remota durante la auditoría.",
        fn="Interceptar sockets de Python no cubre subprocesos ni navegador.",
    ),
    family(
        "QA-45",
        "Representación contractual y mapping aprobados",
        "configuration/operator",
        "Regla válida matemáticamente representa mal el acuerdo",
        "INV-07 INV-08 INV-13",
        "Contrato y ejemplos reales; mínimo por servicio o remito; fecha por componente; columna de importe ambigua.",
        "1. Aplicar pasos 1–10 del protocolo de cliente real. 2. Calcular hoja manual antes de ejecutar el motor. 3. Confirmar representación con el cliente. 4. Preservar hashes y dudas.",
        "Toda regla material tiene responsable y ejemplo independiente; desconocido bloquea certeza, no default de industria.",
        "OR-01 OR-04",
        "IR-15",
        [],
        status="diseñado",
        cost="medio",
        kind="manual",
        real=True,
        human=True,
        effort="según contrato; medir horas",
        when="antes de cliente real; cambio contractual",
        fp="Una práctica nueva no es un bug hasta compararla con el contrato confirmado.",
        fn="Tests sintéticos pueden pasar con contrato equivocado.",
    ),
    family(
        "QA-46",
        "Generalidad de cinco arquetipos",
        "configuration/core",
        "Cliente nuevo requiere excepciones exclusivas",
        "INV-26 INV-13",
        "Arquetipos A–E de QA_CASES; mismos IDs y precios diferentes; E con base por pickup y adicional por delivery.",
        "1. Configurar sin cambiar el core. 2. Calcular manualmente. 3. Ejecutar y registrar archivos modificados. 4. Si E no puede representarse fielmente, documentar la abstracción faltante.",
        "A: 31.5; B: 900; C: bandas, pallets y evidencia; D: 194.25 USD; E: 100 + 12 con acuerdos separados sólo si representan el contrato. Sin condiciones por cliente, sector o transportista en el core.",
        "OR-01 OR-05",
        "IR-15 IR-13",
        ["tests/test_integration.py::test_real_files_three_agreements_golden_and_second_client"],
        severity="HIGH",
        priority="P1",
        cost="medio",
        human=True,
        fp="Un cambio reutilizable y justificado del core no equivale a una excepción exclusiva de cliente.",
        fn="El test existente no ejercita el quinto arquetipo E.",
    ),
    family(
        "QA-47",
        "Paquete y plataforma real",
        "packaging/OS",
        "El checkout funciona pero el paquete instalado pierde recursos o cambia la importación.",
        "INV-21 INV-23",
        "Wheel y sdist recién construidos; directorio fuera del repositorio; Linux y Windows del entorno de uso.",
        "1. Instalar paquete aislado. 2. Comprobar recursos UI, demo, replay y exportación. 3. Comparar contenidos y hashes. 4. En Windows: rutas Unicode, longitudes, saltos de línea y Excel real.",
        "Importación desde paquete instalado sin modo editable; recursos completos y equivalencia económica. Windows pendiente hasta probarlo en una máquina real.",
        "OR-04 OR-06 OR-07",
        "IR-07 IR-08",
        [],
        runners=[".venv/bin/python scripts/verify_delivery.py --output output/delivery-verification.json"],
        status="parcial",
        severity="HIGH",
        priority="P1",
        group="B",
        cost="alto",
        windows=True,
        effort="1–2 días",
        when="release; antes de cliente real",
        fp="Fechas ZIP y hashes del build pueden cambiar sin cambio económico; comparar contenido de archivos.",
        fn="Instalar wheel y sdist en Linux no valida rutas ni Excel de escritorio en Windows.",
    ),
    family(
        "QA-48",
        "Escala, memoria y tiempos de todas las etapas",
        "performance",
        "Un cierre real agota memoria o tiempo y entrega una salida aparentemente completa.",
        "INV-25",
        "10000 operaciones con 50000 y 100000 cargos; trazas completas; tabla de 10000 tarifas; medición por fase.",
        "1. Un proceso por tamaño con memoria base registrada. 2. Medir importación, motor, hashes, persistencia, exportación y UI por separado. 3. Conciliar cantidades y sumas al terminar.",
        "Sin pérdida ni resultado incorrecto y dentro del presupuesto operativo acordado. Las mediciones históricas del core en VERIFICATION.md no constituyen un SLA de todo el flujo.",
        "OR-03 OR-10",
        "IR-12",
        [],
        runners=[
            ".venv/bin/python output/e2e/platform_scale/benchmark_runner.py --sizes 1000 --reps 1 --skip-curve --all-exports --output-dir output/qa48-small"
        ],
        status="parcial",
        severity="HIGH",
        priority="P2",
        group="B",
        cost="alto",
        kind="benchmark",
        effort="1–3 días",
        when="cambio algorítmico; volumen nuevo; release relevante",
        fp="Carga concurrente o máquina distinta pueden cambiar tiempos sin regresión causal.",
        fn="El pipeline de 1000 cargos no extrapola 50000/100000 ni mide un navegador con esos hallazgos.",
    ),
    family(
        "QA-49",
        "Los verificadores detectan corrupción",
        "QA/oracles",
        "Checker pasa todo o importa lógica defectuosa del motor",
        "INV-01 INV-04 INV-23",
        "Corrida válida y copias con confirmada inventada, ID duplicado, suma alterada, estado falso en XLSX y fila faltante.",
        "1. Exigir resultado limpio para la base válida. 2. Alterar una causa por copia. 3. Exigir error identificable y salida 1. 4. Probar entrada malformada con salida 2.",
        "Cada alteración objetivo se detecta. qa/reference.py y qa/invariants.py no importan lógica productiva. El CLI conserva sus validaciones con Python optimizado.",
        "OR-01 OR-03 OR-07",
        "IR-08 IR-06",
        [
            "tests/test_qa_infrastructure.py::test_checker_rejects_economic_corruption",
            "tests/test_qa_infrastructure.py::test_cross_report_reconciliation_and_tamper_detection",
        ],
        status="nuevo",
        kind="mutation; unit",
        fp="Descartar captura incompleta antes de atribuir el fallo al producto.",
        fn="Aceptar una corrida correcta no demuestra que el verificador detecte una incorrecta.",
    ),
    family(
        "QA-50",
        "Mutantes críticos dirigidos",
        "mutation infrastructure",
        "Tests verdes no detectan eliminación de defensas",
        "INV-01 INV-02 INV-06 INV-07 INV-09",
        "qa/mutants.json, copias temporales src/tests/fixtures; baseline sano",
        "1. Validar ancla única. 2. Ejecutar tests base en copia temporal. 3. Aplicar un mutante. 4. Ejecutar sus selectores. 5. Exigir fallo de aserción causal; colección fallida o timeout es inconcluso.",
        "Mutaciones de signo, tolerancia, moneda, versión y evidencia deben fallar por aserción causal. Un sobreviviente bloquea la función afectada hasta investigar. Incompetente o inconcluso no cuenta como detectado.",
        "OR-01 OR-05",
        "IR-06 IR-03",
        ["tests/test_mutation_verdict.py::test_mutant_verdict_requires_selected_causal_assertion"],
        status="nuevo",
        cost="medio",
        kind="mutation",
        effort="2–4 h por mutante nuevo",
        when="cambio de defensa; release; después de incidente",
        fp="Un cambio de API o ancla puede volver obsoleto al mutante; no demuestra equivalencia semántica.",
        fn="La señal causal exigida vale para estos diez mutantes; no demuestra que todas las defensas tengan un mutante dirigido.",
        runners=[".venv/bin/python scripts/qa.py mutate --execute"],
    ),
    family(
        "QA-51",
        "Validación ciega con cliente",
        "field validation",
        "Confundir coincidencia sintética con seguridad económica real",
        "INV-12 INV-13 INV-22",
        "Período real y control histórico bajo custodio separado; seguir REAL_CLIENT_VALIDATION_PROTOCOL.md.",
        "1. Congelar representación y corrida antes de ver control histórico. 2. Comparar por cargo y moneda. 3. Resolver falsos PASS/FAIL y diferencias conocidas, nuevas o desconocidas. 4. Registrar horas de trabajo.",
        "Contraste externo documentado; diferencia nueva correcta no equivale a dinero recuperado. Conservar primera corrida antes de ajustar tras conocer las respuestas.",
        "OR-01 OR-04",
        "IR-15 IR-01 IR-02",
        [],
        status="diseñado",
        cost="alto",
        group="B",
        kind="manual",
        real=True,
        human=True,
        effort="según período; medir",
        when="antes de cliente real; nuevo arquetipo",
        fp="Con distinto alcance o período no se comparan montos directamente.",
        fn="El control histórico también puede estar equivocado; resolver diferencias con evidencia independiente.",
    ),
    family(
        "QA-52",
        "Gate de pago sin nuestra supervisión",
        "release/use policy",
        "Habilitar decisiones de pago sólo por cantidad de tests aprobados.",
        "INV-01 INV-21 INV-25 INV-26",
        "Gate U de RELEASE_CRITERIA.md; evidencia real, operativa y de Windows según alcance.",
        "1. Evaluar cada requisito del Gate U. 2. Registrar pendientes, incidentes y desconocidos. 3. Comprobar restricciones efectivas, restauración, identidad y conciliación del total documental.",
        "Gate U cerrado para 0.1.0. Ninguna estadística sintética lo habilita; pytest no sustituye confirmación del contrato.",
        "OR-01 OR-06 OR-10",
        "IR-15",
        [],
        status="diseñado",
        group="B",
        cost="alto",
        kind="manual",
        real=True,
        human=True,
        effort="no estimable sin piloto",
        when="antes de habilitar decisiones sin supervisión",
        fp="Este gate no impide desarrollo local con datos ficticios.",
        fn="Confundir piloto supervisado con habilitación para decidir pagos sin revisión.",
    ),
    family(
        "QA-53",
        "IDs y JSON inequívocos",
        "serialization/models",
        "Una clave JSON duplicada o colisión de ID cambia la interpretación.",
        "INV-04 INV-26",
        "JSON con clave amount repetida y valores 1 y 100; IDs repetidos por entidad S/C/A/E; datos malformados y campo desconocido.",
        "1. Leer JSON con parser del producto. 2. Validar duplicados por entidad. 3. Verificar rechazos visibles de importación. 4. Probar lector JSON estricto del verificador.",
        "Claves repetidas, números no finitos y campos extra rechazados; ninguna política silenciosa de conservar última fila; duplicados de importación visibles.",
        "OR-04",
        "IR-07 IR-13",
        [
            "tests/test_adversarial.py::test_duplicate_json_keys_are_rejected",
            "tests/test_importing.py::test_duplicate_business_ids_visible_not_silently_deduplicated",
        ],
        kind="fuzz; unit",
        fp="Mismo ID en entidades distintas puede ser válido; unicidad por entidad.",
        fn="Un parser permisivo en QA puede aceptar lo que el producto rechaza.",
    ),
    family(
        "QA-54",
        "Bundle portable y ancla externa",
        "archive/integrity",
        "Paquete alterado parece evidencia confiable",
        "INV-21 INV-22 INV-28",
        "ZIP de demo; alterar archivo, manifest, snapshot o decisión; entradas repetidas, fuente faltante y ruta hostil.",
        "1. Verificar manifest, corrida, cadena de decisiones y fuentes. 2. Comparar hash del ZIP con ancla externa. 3. Alterar un componente por copia. 4. Verificar sin extraer rutas controladas por el archivo.",
        "Alteraciones detectadas respecto del ancla; un manifest consistente consigo mismo no prueba autenticidad. Declarar metadata no cubierta por hashes.",
        "OR-06 OR-09",
        "IR-10 IR-14",
        ["tests/test_storage_reporting.py::test_portable_bundle_integrity"],
        kind="security; integration",
        fp="Reexportar legítimamente un ZIP puede cambiar timestamps y hash del contenedor.",
        fn="Un atacante puede recalcular todos los hashes; sin ancla independiente no hay autenticación.",
    ),
    family(
        "QA-55",
        "Entrega reproducible y dependencias",
        "Git/build/environment",
        "Tests locales prueban archivos distintos de los entregados",
        "INV-21 INV-19",
        "Commit limpio, checkout aislado, lock de dependencias, originales con CRLF y SHA, wheel y sdist.",
        "1. Comparar árbol versionado y archivos materiales. 2. Instalar y probar en checkout limpio. 3. Registrar hashes del paquete y dependencias. 4. Verificar equivalencia de parsing con LF sin exigir SHA del original CRLF.",
        "Código entregado igual al verificado; cada original conserva hash de sus bytes; secretos, bases y salidas fuera de Git. No presumir builds idénticos sin comprobar reproducibilidad.",
        "OR-06 OR-08",
        "IR-09 IR-07",
        [],
        runners=[".venv/bin/python scripts/verify_delivery.py --output output/delivery-verification.json"],
        status="parcial",
        severity="HIGH",
        priority="P1",
        group="B",
        cost="medio",
        effort="4–8 h",
        when="release; cambio de dependencias",
        fp="Normalizar saltos de línea cambia bytes y procedencia; sólo preserva economía si parsing es equivalente.",
        fn="Las instalaciones aisladas en Linux no prueban Excel de escritorio, distribución firmada ni hashes de terceros en el lock.",
    ),
    family(
        "QA-56",
        "Separación de liquidaciones y alcance de obligación",
        "grouping/domain",
        "Sumar cargos de servicios/períodos distintos por clave incompleta",
        "INV-05 INV-09 INV-13",
        "Referencia R; cargos de 100 en liquidaciones L1 y L2; tarifa 100; cliente confirma dos servicios independientes.",
        "1. Revisar group_key y contrato. 2. Auditar sin período en clave. 3. Representar período y servicio explícitos con operaciones correctas. 4. Comparar grafo de obligaciones manual.",
        "L1 y L2 conservan hallazgos separados. Si reutilizan la misma operación/concepto: REVIEW y confirmada0; otra liquidación no prueba otro servicio. Operaciones distintas correctamente vinculadas pueden ser PASS. La asignación entre facturas requiere representación contractual explícita.",
        "OR-01 OR-05",
        "IR-04 IR-15",
        [
            "tests/test_review_regressions.py::test_rebilling_same_operation_in_other_invoice_is_not_independent_pass",
            "tests/test_review_regressions.py::test_separate_operations_on_separate_invoices_still_pass",
        ],
        status="parcial",
        human=True,
        cost="medio",
        effort="4–8 h",
        when="nuevo formato; cambio de matching; antes de cliente real",
        fp="Dos líneas de facturas pueden completar un servicio; no asumir independencia automáticamente.",
        fn="Fixtures de un único período no ejercitan este error causal.",
    ),
    family(
        "QA-57",
        "Diagnóstico no muta evidencia",
        "QA/forensics",
        "La herramienta de diagnóstico inicializa o migra la base original.",
        "INV-30 INV-28",
        "Base de sólo lectura; schema futuro o incompleto; fila JSON corrupta; hashes previos.",
        "1. Ejecutar impact en sólo lectura. 2. Intentar ruta inexistente. 3. Comparar bytes, schema y triggers antes/después. 4. Corrupción debe aparecer como unknown o error global explícito.",
        "No invocar Store, crear bases ni instalar triggers. La corrupción nunca produce una selección vacía que aparente ausencia de impacto.",
        "OR-06 OR-09",
        "IR-12 IR-14",
        ["tests/test_qa_infrastructure.py::test_impact_is_read_only_and_retains_unknowns"],
        status="nuevo",
        fp="Una base activa puede cambiar por otro proceso; preservar copia consistente para comparar hashes.",
        fn="Comprobar sólo mtime no demuestra ausencia de modificaciones.",
    ),
    family(
        "QA-58",
        "Píxel exacto y matrices visuales exhaustivas",
        "cosmetic UI",
        "Desviación estética sin impacto en la lectura.",
        "INV-23 (sólo si cambia significado)",
        "Todas las combinaciones de sistemas operativos, fuentes y anchos; sin defectos económicos conocidos.",
        "1. Diferir igualdad exacta de píxeles. 2. Cubrir texto, contraste y desbordamiento material en QA-39. 3. Reconsiderar ante fallo real de lectura.",
        "Diferir matriz estética exhaustiva. Cualquier importe o etiqueta ocultos se clasifican como QA-39/P0.",
        "OR-07",
        "IR-08",
        [],
        severity="LOW",
        priority="P3",
        group="C",
        cost="alto",
        status="diferido",
        kind="E2E",
        likelihood=2,
        detection=1,
        effort="diferido",
        when="sólo si aparece necesidad material",
        fp="Antialiasing o fuentes distintas producen diferencias visuales sin error operativo.",
        fn="Diferir pruebas cosméticas no permite ocultar moneda o estado.",
    ),
]
