"""Authored causal test families. Markdown/CSV/backlog are generated from these records."""


def family(
    identifier,
    name,
    component,
    risk,
    invariant,
    fixture,
    steps,
    expected,
    oracle,
    incident,
    selectors=(),
    *,
    severity="CRITICAL",
    priority="P0",
    group="A",
    cost="bajo",
    kind="integration",
    status="parcial",
    likelihood=3,
    detection=4,
    fp,
    fn,
    effort="2–6 h",
    when="cambio afectado; CI; release; después de incidente",
    real=False,
    windows=False,
    human=False,
):
    impact = {"CRITICAL": 5, "HIGH": 4, "MEDIUM": 2, "LOW": 1}[severity]
    divisor = {"trivial": 1, "bajo": 2, "medio": 4, "alto": 8}[cost]
    return {
        "TEST_ID": identifier,
        "NOMBRE": name,
        "COMPONENTE": component,
        "RIESGO": risk,
        "SEVERIDAD": severity,
        "INVARIANTE": invariant,
        "PRECONDICIONES": "Entorno aislado; originales preservados; expected independiente. Base B y matrices exactas en QA_CASES.md.",
        "FIXTURE_DATOS": fixture,
        "PASOS_EXACTOS": steps,
        "RESULTADO_ESPERADO": expected,
        "ORACULO": oracle,
        "FALLA": "Cualquier contradicción al resultado esperado, omisión de salida requerida o excepción sin clasificar. Una prueba no ejecutada queda pendiente.",
        "FALSOS_POSITIVOS": fp,
        "FALSOS_NEGATIVOS": fn,
        "AUTOMATIZABLE": "parcialmente" if human or real else "sí",
        "TIPO_IDEAL": kind,
        "COSTO_EJECUCION": cost,
        "VALOR_ESPERADO": "crítico"
        if severity == "CRITICAL"
        else "alto"
        if severity == "HIGH"
        else "medio"
        if severity == "MEDIUM"
        else "bajo",
        "PRIORIDAD": priority,
        "GRUPO": group,
        "CUANDO": when,
        "RESPUESTA_SI_FALLA": incident + " + IR-COMMON (INCIDENT_RESPONSE.md)",
        "ESTADO_COBERTURA": status,
        "SELECTORES": list(selectors),
        "IMPACTO": impact,
        "PROBABILIDAD": likelihood,
        "DIFICULTAD_DETECCION": detection,
        "RIESGO_SCORE": impact * likelihood * detection,
        "VALOR_POR_COSTO": impact * likelihood * detection / divisor,
        "ESFUERZO_IMPLEMENTACION": effort,
        "DATOS_REALES": real,
        "WINDOWS": windows,
        "INTERVENCION_HUMANA": human,
    }


FAMILIES = [
    family(
        "QA-01",
        "Certeza y diferencia confirmada",
        "engine/summary",
        "Falta de respaldo se convierte en discrepancia objetiva",
        "INV-01 INV-10 INV-11",
        "B; A=200,E=100; requisito approval ausente; repetir con issue row y con versión ausente",
        "1. Auditar cada variante por separado. 2. Inspeccionar finding y todos los buckets. 3. Pasar run al checker independiente.",
        "Sin evidencia: REVIEW,E100,Δ100,confirmada0; issue row impide PASS/FAIL; sin versión UNDETERMINABLE/E null. Ningún bucket confirma100.",
        "OR-03 OR-05",
        "IR-03",
        [
            "tests/test_engine.py::test_missing_evidence_does_not_confirm_even_numeric_difference",
            "tests/test_engine.py::test_import_rejects_block_economic_confirmation",
        ],
        fp="Una decisión APPROVED posterior no cambia status del motor.",
        fn="Comprobar sólo finding y no summary/reportes deja escapar dinero confirmado.",
    ),
    family(
        "QA-02",
        "Tolerancia, signo y fronteras",
        "comparison",
        "PASS fuera de tolerancia o FAIL en el límite",
        "INV-02 INV-03",
        "B y N05,N06,N07; E=100/200; límites positivos y negativos",
        "1. Ejecutar A=T exacta y T±0.01 respecto de E. 2. Recalcular T y Δ con Fraction. 3. Revisar PASS/FAIL y neto/brutos.",
        "E100,T0.01,A100.01 PASS;100.02 FAIL+0.02;99.98 FAIL−0.02. E200,rel0.05,A210 PASS;210.01 FAIL10.01.",
        "OR-01 OR-02",
        "IR-01 IR-02 IR-06",
        [
            "tests/test_engine.py::test_tolerance_and_signed_differences",
            "tests/test_qa_infrastructure.py::test_generated_reference_prices",
        ],
        kind="property-based; mutation",
        fp="Confundir Δ calculada de un PASS con confirmada0.",
        fn="Tolerancia relativa, negativo o igualdad exacta no ejercitados.",
    ),
    family(
        "QA-03",
        "Referencia de precio independiente",
        "rules",
        "Fórmula incorrecta coincide con golden generado por el mismo motor",
        "INV-03 INV-14 INV-15",
        "N08,N09; casos generados unit/min/percent; anclas31.5 y42",
        "1. Comprobar anclas de referencia. 2. Generar q/tarifa/mínimo/factor. 3. Comparar E con referencia racional sin importar helpers productivos.",
        "q10×2,min30,+5%→31.5; q20→42. Igual E y A no produce FAIL; cambiar A no cambia E.",
        "OR-01 OR-02",
        "IR-06",
        [
            "tests/test_qa_infrastructure.py::test_reference_manual_anchors",
            "tests/test_qa_infrastructure.py::test_generated_reference_prices",
        ],
        kind="property-based; differential",
        status="nuevo",
        fp="Referencia fuera de su subconjunto no es fallo del motor.",
        fn="Ambos calculan bien pero contrato mal representado; validar OR-01.",
    ),
    family(
        "QA-04",
        "Dominio numérico y tipos estrictos",
        "models/canonical",
        "Coerción, no finito o desborde se acepta como dinero",
        "INV-14 INV-27",
        "N17..N20; float0.1,bool1,NaN,37 dígitos,13 decimales; agregar dos inputs36dígitos",
        "1. Validar cada input. 2. Auditar suma de inputs válidos grandes. 3. Verificar rechazo antes de conclusión o suma exacta.",
        "Inputs inválidos rechazados; 36nueves+1 suma37 dígitos permitida. No coerción bool→decimal ni 1→boolean.",
        "OR-01 OR-03",
        "IR-06",
        [
            "tests/test_engine.py::test_float_prohibited",
            "tests/test_engine.py::test_invalid_money",
            "tests/test_adversarial.py::test_aggregate_amount_can_exceed_individual_input_digit_bound",
            "tests/test_adversarial.py::test_no_boolean_coercion",
        ],
        kind="unit; property-based",
        fp="Aplicar límites de input a agregados internos legítimos.",
        fn="Sólo validar Value y omitir Charge/importer.",
    ),
    family(
        "QA-05",
        "Redondeo, escala y orden",
        "rules/currency_round",
        "Cambio de centavos por modo u orden implícito",
        "INV-15 INV-27",
        "N11..N16; 0.005+0.005; valores negativos; escalas0,2,3,8",
        "1. Ejecutar cada fila manual. 2. Diferenciar round final de dos round explícitos. 3. Comprobar escala/modo/input en trace.",
        "Final0.01; por componente0.02; HALF_EVEN2.345→2.34,2.355→2.36. HALF_DOWN rechazado por configuración.",
        "OR-01 OR-02",
        "IR-06",
        [
            "tests/test_qa_infrastructure.py::test_reference_manual_anchors",
            "tests/test_qa_infrastructure.py::test_generated_reference_prices",
        ],
        kind="property-based; mutation",
        fp="Cambiar expresión contractual es cambio esperado, no invariancia.",
        fn="Sólo positivos/escala2 no detecta truncamiento de créditos.",
    ),
    family(
        "QA-06",
        "División y contexto ambiental",
        "rules/Decimal",
        "Contexto global o precisión cambia resultado sin permiso",
        "INV-14 INV-19",
        "N21..N23; prec global6; numeradores/denominadores negativos; divisor0",
        "1. Comparar división con Decimal alta precisión y casos manuales. 2. Cambiar/restaurar contexto externo. 3. Probar precisión insuficiente.",
        "1/3→0.33;−1/8 HALF_EVEN→−0.12; divisor0/desborde→UNDETERMINABLE/0confirmado. Contexto ajeno no altera audit.",
        "OR-01 OR-08",
        "IR-06",
        [
            "tests/test_engine.py::test_property_division_matches_high_precision",
            "tests/test_engine.py::test_global_decimal_context_does_not_affect_results",
            "tests/test_adversarial.py::test_inexact_comparison_becomes_undeterminable",
        ],
        kind="property-based",
        fp="Referencia Decimal con precisión insuficiente introduce doble redondeo.",
        fn="Rango actual de enteros pequeños no cubre todo exponente válido.",
    ),
    family(
        "QA-07",
        "Unidades y monedas separadas",
        "models/rules/summary",
        "Kg, gramos o monedas se suman como equivalentes",
        "INV-06 INV-13",
        "B+segundo cargoUSD; N24,N25; unidad final vacía o kg",
        "1. Auditar moneda discordante. 2. Introducir g frente a kg sin factor. 3. Añadir factor explícito y acuerdoUSD independiente.",
        "Discordancia→UNDETERMINABLE; sin factor no conversión; 1000g×0.001kg/g×2ARS/kg=2ARS; buckets separados.",
        "OR-01 OR-03",
        "IR-06",
        [
            "tests/test_engine.py::test_currencies_never_summed_or_converted",
            "tests/test_engine.py::test_missing_attribute_and_unit_mismatch",
            "tests/test_engine.py::test_rules_need_currency_units",
        ],
        kind="unit; metamorphic",
        fp="No imponer dos decimales por código ISO.",
        fn="Revisar core pero permitir suma multimoneda en UI.",
    ),
    family(
        "QA-08",
        "Números desde originales",
        "CSV/XLSX importer",
        "Cambio silencioso de magnitud o precisión antes del motor",
        "INV-14 INV-22",
        "XLSX literal1000000000000000.01 y1e999999; CSV1.234,56 y1.23,45; corpus exacto",
        "1. Preservar bytes. 2. Importar con mapping confirmado. 3. Comparar value y provenance.raw con literal independiente.",
        "XLSX preserva fracción; exponente extremo rechaza fila; CSV argentino1234.56; agrupador inválido rechaza, no corrige silenciosamente.",
        "OR-04",
        "IR-07",
        [
            "tests/test_importing.py::test_xlsx_preserves_original_decimal_literal_without_binary_float_loss",
            "tests/test_importing.py::test_xlsx_unbounded_exponent_is_rejected_before_decimal_expansion",
            "tests/test_importing.py::test_argentine_decimal",
            "tests/test_importing.py::test_unsafe_numeric_strings_rejected",
        ],
        kind="fuzz; property-based",
        fp="Un string XLSX respeta locale; no tratarlo igual que celda numérica.",
        fn="Leer expected mediante openpyxl repite el float defectuoso.",
    ),
    family(
        "QA-09",
        "Identidad y normalización declarada",
        "mapping/models",
        "Ceros o caracteres alterados unen entidades distintas",
        "INV-09 INV-22",
        "ref texto00001; numérico1 con máscara00000; fraccional99999999999999.001; Unicode y espacios",
        "1. Importar referencia textual. 2. Repetir numeric_text reject/formatted. 3. Verificar reglas de strip y concepto desconocido.",
        "00001 se conserva; numérico requiere política; fraccional rechaza aunque float parezca entero; concepto desconocido queda external:valor.",
        "OR-04 OR-05",
        "IR-04 IR-07",
        [
            "tests/test_importing.py::test_xlsx_numeric_id_requires_explicit_policy",
            "tests/test_importing.py::test_original_fractional_numeric_identifier_cannot_become_integer_after_float_rounding",
            "tests/test_importing.py::test_unknown_concept_not_canonicalized_by_accident",
        ],
        fp="Strip externo está declarado en modelos; no prometer byte equality del valor normalizado.",
        fn="Alias/Unicode normalizado fuera del mapping puede colisionar en un cliente.",
    ),
    family(
        "QA-10",
        "Estructura CSV y conservación de filas",
        "CSV importer",
        "Fila o columna se desplaza u omite sin rastro",
        "INV-12 INV-22",
        "Quotes multilínea, BOM, cp1252, header duplicado/vacío, fila con columna extra, reordered columns",
        "1. Importar corpus con líneas físicas anotadas. 2. Comparar aceptadas/rechazadas y raw. 3. Permutar columnas/mapping.",
        "Referencia multilínea mantiene siguiente registro en línea4; mapeada repetida/ausente error; valor extra rechaza; economía invariante al reordenar.",
        "OR-04 OR-08",
        "IR-07 IR-11",
        [
            "tests/test_adversarial.py::test_csv_multiline_provenance_uses_actual_line",
            "tests/test_importing.py::test_ambiguous_or_missing_headers_fail_file",
            "tests/test_importing.py::test_reordered_columns_same_normalized_records",
            "tests/test_adversarial.py::test_oversized_unmapped_cells_not_silently_shifted",
        ],
        kind="fuzz; metamorphic",
        fp="Blank lines/headers no son cargos; definir población relevante.",
        fn="Control sólo de cantidad deja desplazamiento con misma cantidad.",
    ),
    family(
        "QA-11",
        "Semántica de libro Excel",
        "XLSX importer",
        "Fórmula, ocultamiento o merge cambia alcance percibido",
        "INV-12 INV-14 INV-22",
        "Libro2hojas/hiddenrows/merged/date styles/formula con cache; ver corpus en QA_CASES",
        "1. Especificar sheet. 2. Importar con columnas requeridas vacías/merged. 3. Añadir fórmula cacheada y fila oculta. 4. Cotejar alcance declarado.",
        "Varias hojas sin selección error; fórmula mapeada rechazada; sin fill-forward. Ocultas requieren alcance visible: falta automatizar warning en producto.",
        "OR-04",
        "IR-07 IR-15",
        [
            "tests/test_importing.py::test_multisheet_requires_selection",
            "tests/test_importing.py::test_xlsx_formula_never_evaluated_or_taken_as_cache",
            "tests/test_importing.py::test_original_numeric_tokens_follow_sparse_sheet_coordinates",
        ],
        cost="medio",
        kind="fuzz; manual",
        human=True,
        fp="Fila oculta puede ser legítima; no descartarla por defecto.",
        fn="Happy path XLSX no cubre estilos/hidden/cache; deuda explícita.",
    ),
    family(
        "QA-12",
        "XLS legacy y cache explícito",
        "xlrd/importer",
        "Fórmula guardada o binario impreciso parece hecho verificado",
        "INV-14 INV-22",
        "XLS BIFF con valores/fórmulas guardadas, codepage, epochs; montos alta precisión",
        "1. Importar sin allow_xls_cached_values. 2. Habilitar y revisar warning. 3. Cotejar pares de celdas fuera de xlrd.",
        "Sin aceptación error; con aceptación warning persistente. No declarar recuperación de precisión perdida ni garantía de recalculado.",
        "OR-04",
        "IR-07",
        ["tests/test_importing.py::test_xls_requires_explicit_cached_value_acceptance"],
        severity="HIGH",
        priority="P1",
        cost="medio",
        human=True,
        kind="fuzz; manual",
        fp="Warning esperado no es fallo; su ausencia sí.",
        fn="XLS generado por xlwt no cubre todos los productores reales.",
    ),
    family(
        "QA-13",
        "Límites de importación y corrupción",
        "file parser/API",
        "Archivo agota recursos o produce un lote parcial silencioso",
        "INV-12 INV-25",
        "Archivo25MiB+, ZIP declarado150MiB+,250columnas+,200001filas+,bytes truncados",
        "1. Crear cabeceras/payloads pequeños que activen límites. 2. Ejecutar en subprocess con timeout/RSS. 3. Comprobar clasificación y ausencia de corrida parcial.",
        "ImportErrorDetail/422 útil antes de agotar recursos; ningún resultado económico confirmado para importación abortada.",
        "OR-09 OR-10",
        "IR-07 IR-14",
        ["tests/test_importing.py::test_malformed_xlsx_fuzz_is_bounded_and_classified"],
        severity="HIGH",
        priority="P1",
        group="B",
        cost="alto",
        kind="fuzz; security",
        effort="1–2 días",
        fp="Timeout del equipo saturado requiere repetir aislado una vez.",
        fn="Bytes aleatorios cortos no atraviesan parser profundo; tamaño declarado no prueba expansión real.",
    ),
    family(
        "QA-14",
        "Importación incompleta y alcance documental",
        "import/core/operator",
        "Total aceptado se confunde con total factura",
        "INV-11 INV-12 INV-29",
        "B con fila importe inválida; documento externo total200 mientras aceptado100; archivo faltante",
        "1. Contar filas de negocio. 2. Conciliar accepted/rejected/omitted. 3. Auditar issue row. 4. Comparar contra total externo y etiqueta UI.",
        "Rechazo impide certeza del lote. Archivo nunca aportado no se detecta por core: control externo obligatorio y déficit visible.",
        "OR-03 OR-04 OR-01",
        "IR-02 IR-07",
        [
            "tests/test_engine.py::test_import_rejects_block_economic_confirmation",
            "tests/test_integration.py::test_invalid_fixture_rejects_visible_rows",
        ],
        human=True,
        fp="Subtotal/cabecera no es fila económica duplicada.",
        fn="Import_complete=true no demuestra documentos completos.",
    ),
    family(
        "QA-15",
        "Procedencia verificable",
        "import/trace/storage",
        "Dato usado no puede reconstruirse desde original",
        "INV-22",
        "CSVmultilínea, XLSXfila3, constante mapping; original con un byte cambiado",
        "1. Del finding seguir trace.field→registro→SourceRef. 2. Verificar SHA y localizar celda. 3. Contrastar raw→transform→value, incluidas constantes.",
        "Documento/hoja/fila/columna/raw correctos y mapping congelado; archivo alterado se rechaza; constante respaldada por configuración.",
        "OR-04 OR-06",
        "IR-11",
        [
            "tests/test_importing.py::test_csv_argentine_numbers_zeroes_and_provenance",
            "tests/test_storage_reporting.py::test_tampered_source_detected",
        ],
        human=True,
        fp="Dataset manual puede carecer de provenance por contrato actual; exigirla en importados.",
        fn="Hash correcto de archivo no demuestra referencia a la celda correcta.",
    ),
    family(
        "QA-16",
        "Selección única de vigencia",
        "engine.select_version",
        "Tarifa equivocada por frontera/gap/overlap",
        "INV-07 INV-08 INV-16",
        "QA_CASES calendario V1=100/V2=120, fin06-30/inicio07-01; versiones invertidas",
        "1. Evaluar comienzo/fin/día siguiente. 2. Crear overlap/gap. 3. Invertir orden de versiones. 4. Consolidar fechas de ambos lados.",
        "Extremos inclusivos; cero/dos versiones o grupo mixto→UNDETERMINABLE; no elegir primera ni prorratear.",
        "OR-05",
        "IR-05",
        [
            "tests/test_engine.py::test_version_boundaries",
            "tests/test_engine.py::test_overlapping_versions_never_pick_first",
            "tests/test_engine.py::test_group_mixed_version_is_undeterminable",
        ],
        kind="property-based; mutation",
        fp="Día dentro de versión puede ser FAIL por importe, no por fecha.",
        fn="Dos versiones con mismo precio ocultan selector equivocado.",
    ),
    family(
        "QA-17",
        "Fecha civil y seriales de Excel",
        "import/date types",
        "Fecha cambia por locale/época/hora y selecciona otra tarifa",
        "INV-08 INV-22",
        "Matriz temporal completa:03/04 ambiguo, leap2024/2026, serial60, epochs1900/1904, midnight/offset",
        "1. Importar cada par fuente→fecha esperada. 2. Repetir con TZs distintas. 3. Comparar versión seleccionada con calendario manual.",
        "Ambigua/invalid/hora/zona→rechazo; medianoche ingenua admitida. Serial ficticio60 debe bloquearse/advertirse: pendiente comprobar y corregir si normaliza.",
        "OR-04 OR-05",
        "IR-05 IR-07",
        [
            "tests/test_importing.py::test_ambiguous_date_is_rejected",
            "tests/test_importing.py::test_timestamps_are_not_silently_truncated",
            "tests/test_engine.py::test_alternate_date_field",
        ],
        kind="fuzz; property-based",
        cost="medio",
        fp="Cambiar date_field contractual legítimamente cambia tarifa.",
        fn="Comparar sólo date final pierde serial/epoch original.",
    ),
    family(
        "QA-18",
        "Reglas/condiciones y AST acotado",
        "models/rules",
        "Default inventado o condición desconocida se trata falsa",
        "INV-07 INV-13",
        "B con0/2reglas aplicables, condición ausente, if lazy, op desconocida, profundidad31",
        "1. Validar AST inválidos. 2. Evaluar datos faltantes. 3. Probar rama no elegida con división0. 4. Repetir reglas reordenadas.",
        "AST inválido rechaza;0/2reglas→UNDETERMINABLE; if no evalúa rama no elegida; condición faltante no es false.",
        "OR-01 OR-05",
        "IR-03 IR-06",
        [
            "tests/test_engine.py::test_condition_missing_is_not_false",
            "tests/test_engine.py::test_condition_branch_is_lazy",
            "tests/test_engine.py::test_overlapping_rules_are_undeterminable",
            "tests/test_adversarial.py::test_bounded_expression_depth_rejects_nested_attack",
        ],
        fp="and/or actualmente evalúan todos los operandos; sólo if promete lazy.",
        fn="Test AST parseado no prueba aridad/semántica de cada operador.",
    ),
    family(
        "QA-19",
        "Lookup/bandas sin desempate arbitrario",
        "rules/tables",
        "Primer precio coincidente reemplaza ambigüedad real",
        "INV-07 INV-13 INV-16",
        "N10, tabla con clave repetida/mismo precio, gap/overlap, unidadesdiscordantes",
        "1. Evaluar ambos lados y límite exacto. 2. Repetir filas. 3. Invertir tabla. 4. Intercalar versión con tabla homónima diferente.",
        "Bandas[lower,upper); exactamente1coincidencia. Cero/dos incluso mismo importe→UNDETERMINABLE; caché separada por versión/acuerdo.",
        "OR-05",
        "IR-05 IR-06",
        [
            "tests/test_adversarial.py::test_band_overlap_and_gap_never_select_arbitrarily",
            "tests/test_adversarial.py::test_duplicate_lookup_rows_even_same_price_are_ambiguous",
        ],
        kind="property-based; mutation",
        fp="Orden textual de tabla puede cambiar hash, economía no.",
        fn="Mismo valor en tablas distintas oculta contaminación de caché.",
    ),
    family(
        "QA-20",
        "Claves, aliases y vínculos explícitos",
        "matching",
        "Entidad equivocada por resolución implícita",
        "INV-09 INV-26",
        "Taxonomía matching1→1/compuesto/alias; clave vacía; explícito inválido/contradictorio",
        "1. Dibujar grafo manual. 2. Aplicar alias sólo al cargo. 3. Vaciar clave. 4. Añadir link inválido y verificar sin fallback.",
        "Match exacto declarado; vacíos no empatan; link ausente/repetido/carrier ajeno→UNDETERMINABLE. Contradicción link/claves requiere control adicional pendiente.",
        "OR-05",
        "IR-04",
        [
            "tests/test_engine.py::test_composite_keys_and_directional_alias",
            "tests/test_engine.py::test_invalid_explicit_link_never_falls_back",
            "tests/test_adversarial.py::test_empty_keys_never_join_to_empty_keys",
        ],
        fp="Precedencia explicit sobre keys es contrato actual; no confundirla con detección de intención errónea.",
        fn="Explicito válido estructuralmente puede apuntar a operación equivocada.",
    ),
    family(
        "QA-21",
        "Ambigüedad propagada a grupos parciales",
        "matching/aggregation",
        "FAIL falso por comparar sólo fracción asignada",
        "INV-09 INV-04",
        "S1/S2 misma referencia; C1=40 explícitoS1,C2=60 ambiguo; E100",
        "1. Auditar en ambos órdenes. 2. Inspeccionar los dos findings. 3. Resolver C2 explícitamente y volver a auditar nueva copia.",
        "Antes: ambos REVIEW/confirmada0; después, si C1+C2→S1, grupoA100,E100 PASS. Ningún cargo se pierde.",
        "OR-03 OR-05",
        "IR-04 IR-03",
        [
            "tests/test_adversarial.py::test_ambiguous_allocation_also_blocks_related_partial_group",
            "tests/test_engine.py::test_matching_ambiguity_is_review",
        ],
        fp="No exigir un único finding antes/después; cambia agrupación.",
        fn="Revisar sólo cargo ambiguo deja FAIL parcial en el otro.",
    ),
    family(
        "QA-22",
        "Consolidado y cargos por componentes",
        "matching/rules",
        "Expected repetido en1→N o N→1 incompleto",
        "INV-04 INV-05 INV-09",
        "S1peso10,S2peso20;group lote;tarifa2; C40+C20; duplicate_fields vacío",
        "1. Auditar sum×2. 2. Dividir/reunir líneas actual. 3. Cambiar sum por attr sobre pesos distintos. 4. Comparar scopes, no IDs hash.",
        "UnE60,A60 PASS; split no repiteE. attr de pesos distintos→UNDETERMINABLE; no prorrateo automático.",
        "OR-02 OR-03 OR-08",
        "IR-04 IR-06",
        [
            "tests/test_engine.py::test_group_sum_and_one_expected_charge",
            "tests/test_engine.py::test_multiple_lines_aggregate_without_inventing_duplicates",
        ],
        kind="property-based; metamorphic",
        fp="Mínimo por envío no es aditivo; no aplicar MT12 fuera de sus precondiciones.",
        fn="N→M solapado no se cubre con N→1.",
    ),
    family(
        "QA-23",
        "Asignaciones superpuestas y servicios parciales",
        "allocation",
        "Misma obligación se confirma dos veces",
        "INV-09 INV-05",
        "C1→S1,S2;C2→S2,S3 mismo concepto; servicio tramo parcial sin política",
        "1. Construir grafo con intersecciónS2. 2. Auditar. 3. Verificar grupo relacionado no confirma ni reparte. 4. Confirmar límite contractual con operador.",
        "Grupos superpuestos REVIEW; no multiplicar expected confirmado. Servicio parcial no representado se bloquea hasta definir regla.",
        "OR-05",
        "IR-04 IR-15",
        ["tests/test_engine.py::test_overlap_allocations_are_review"],
        human=True,
        fp="Conceptos independientes sobre mismo S no son el mismo scope económico.",
        fn="Solapamiento a través de acuerdos distintos requiere revisión contractual.",
    ),
    family(
        "QA-24",
        "Duplicados candidatos y remito legítimo",
        "matching",
        "Deduplicar importe válido o confirmar sospecha",
        "INV-17 INV-04",
        "Dos cargos refigual/conceptigual/importeigual; clavesduplicado activas/inactivas; conceptos distintos",
        "1. Auditar con duplicate_fields. 2. Desactivar sólo esa política. 3. Separar conceptos y verificar conservación.",
        "Candidatos→REVIEW, no eliminación ni ahorro; sin política líneas agregadas; distinto concepto no es duplicado por referencia sola.",
        "OR-03 OR-05",
        "IR-03 IR-04",
        [
            "tests/test_engine.py::test_configured_duplicate_is_candidate_only",
            "tests/test_engine.py::test_same_remittance_different_concepts_is_not_duplicate",
        ],
        fp="Mismo remito legítimo puede requerir claves más específicas.",
        fn="No configurar duplicate_fields no demuestra ausencia de duplicados reales.",
    ),
    family(
        "QA-25",
        "Evidencia por ámbito y adición selectiva",
        "evidence",
        "Respaldo ajeno o insuficiente certifica cargo",
        "INV-10 INV-20",
        "DosS,each_shipment/each_charge/group,any_of approval/POD,document_required; evidencia ajena",
        "1. Retirar un respaldo por ámbito. 2. Agregar sólo el faltante. 3. Comparar grupos no relacionados y run original. 4. Retirar documento obligatorio.",
        "Faltante→REVIEW; evidencia suficiente sólo resuelve scope pertinente; nueva corrida puede PASS o FAIL según Δ, historia intacta.",
        "OR-05 OR-08",
        "IR-03 IR-11",
        [
            "tests/test_engine.py::test_evidence_any_of_and_per_operation",
            "tests/test_engine.py::test_unrelated_evidence_cannot_support_charge",
        ],
        kind="property-based; metamorphic",
        fp="Añadir respaldo puede convertir REVIEW en FAIL legítimo; no exigir PASS.",
        fn="Sólo kind sin revisar asociaciones/document_hash es falso respaldo.",
    ),
    family(
        "QA-26",
        "Cobertura explícita de cargos ausentes",
        "coverage",
        "Inventar deuda o duplicar hallazgo de cobertura",
        "INV-18 INV-04",
        "B sin cargos;rule.expected true; coverage vacío/explícito; versión ausente; carrier incorrecto",
        "1. Comparar sin/con coverage. 2. Probar when=false. 3. Agregar cargo ya indeterminado. 4. Validar scope inválido.",
        "Sin scope no inventar; scope correcto→REVIEW A0 sin confirmada; whenfalse omite expectativa; no duplica cargo sin versión; scope inválido rechaza.",
        "OR-03 OR-05",
        "IR-03 IR-04",
        [
            "tests/test_engine.py::test_missing_expected_charge_requires_explicit_scope_and_is_review",
            "tests/test_adversarial.py::test_missing_coverage_must_not_duplicate_existing_undetermined_charge",
            "tests/test_adversarial.py::test_coverage_cannot_silently_drop_wrong_carrier",
        ],
        fp="Hallazgo sin cargo aumenta findings pero no charge_counts.",
        fn="Creer que cobertura detecta documento faltante no aportado.",
    ),
    family(
        "QA-27",
        "Conservación total por ID y moneda",
        "aggregate/all states",
        "Omisión o doble conteo queda oculto por neto",
        "INV-03 INV-04 INV-05 INV-06",
        "B extendido PASS/FAIL±/REVIEW/UNDETERMINABLE; cargo unmatched;0/negativos; dosmonedas",
        "1. Checker recompone Counter de charge_ids y sumas desde C. 2. Comparar todos los buckets/counts. 3. Mutar salida duplicando/quitando cargo.",
        "Cada C exactamente1vez; bruto por moneda preservado; +50 y−75 separados y neto−25. Checker rechaza salida manipulada.",
        "OR-03",
        "IR-01 IR-02 IR-06",
        ["tests/test_qa_infrastructure.py::test_checker_rejects_economic_corruption"],
        kind="property-based; mutation",
        status="nuevo",
        fp="Créditos invalidan desigualdad determinable≤actual; usar identidades firmadas.",
        fn="Totales coincidentes pueden ocultar omisión y duplicación compensadas: contar IDs.",
    ),
    family(
        "QA-28",
        "Determinismo y transformaciones",
        "core/canonical/import",
        "Orden/nombre/ambiente modifica dinero",
        "INV-19 INV-21",
        "MT01..MT20 con nivel de igualdad declarado; A/B/A; cambio future/filename/columns",
        "1. Guardar baseline completo. 2. Aplicar una transformación. 3. Comparar resultado o economic_projection según tabla. 4. Comprobar fuente hash cambia cuando bytes cambian.",
        "Reordenamiento normalizado completo igual; renombre/columna economía igual aunque snapshot hash cambie; cambio futuro no muta run guardado.",
        "OR-08",
        "IR-09",
        [
            "tests/test_engine.py::test_property_arbitrary_row_permutation",
            "tests/test_engine.py::test_semantic_hash_ignores_incidental_label",
            "tests/test_qa_infrastructure.py::test_generated_uncertainty_and_metamorphism",
        ],
        kind="metamorphic; property-based",
        fp="Exigir semantic_hash igual al agregar versión futura produce falso fallo.",
        fn="Dos errores idénticos satisfacen relación; combinar OR02/03.",
    ),
    family(
        "QA-29",
        "Aislamiento entre clientes y catálogos",
        "configuration/storage/cache",
        "Acuerdo o datoB influyeA sin alarma",
        "INV-26",
        "DosDB, mismosS/C/A/tableIDs; Aprecio100,B900; import originales distintos",
        "1. EjecutarA/B/A en proceso. 2. Reabrir DBs y comparar A. 3. Intentar selección de config ajena en UI y revisar operación.",
        "A idéntico, fuentes/configs separadas por DB. Catálogo global dentro mismaDB no es aislamiento multiempresa; no habilitarlo como tal.",
        "OR-05 OR-06 OR-08",
        "IR-13",
        [],
        status="diseñado",
        cost="medio",
        human=True,
        fp="Diferencia de label/input_hash no prueba contaminación económica.",
        fn="DatosconIDsdistintos nunca ejercitan colisión/caché compartida.",
    ),
    family(
        "QA-30",
        "Decisiones humanas y cadena",
        "storage/UI",
        "Resolución borra finding o decisión previa",
        "INV-20 INV-24",
        "RunB;APPROVED→REJECTED; dos escritores; finding/evidence ajenos",
        "1. Guardar hash de resultado. 2. Añadir decisiones en orden/concurrentes. 3. Verificar chain/resultado. 4. Intentar referencias ajenas.",
        "Resultado original idéntico; decisiones append-only ordenadas/hash enlazado; referencias inexistentes rechazadas.",
        "OR-06",
        "IR-10",
        [
            "tests/test_storage_reporting.py::test_human_decision_never_rewrites_finding",
            "tests/test_storage_reporting.py::test_decision_chain_serializes_concurrent_writers",
            "tests/test_storage_reporting.py::test_no_unknown_decision_or_evidence",
        ],
        fp="Hash de paquete cambia al añadir decisión legítima.",
        fn="Cadena local no detecta truncamiento de sufijo sin ancla externa.",
    ),
    family(
        "QA-31",
        "Integridad histórica y mutación",
        "SQLite/snapshot",
        "Corrida alterada sigue pareciendo confiable",
        "INV-20 INV-28",
        "CopiaDB; UPDATE/DELETE normales y bypass de trigger controlado en copia; cambio deV2",
        "1. Guardar ancla externa. 2. Intentar mutación. 3. Comparar load y list_runs ante byte alterado. 4. Abrir original intacto.",
        "Writes históricos bloqueados; load detecta hashes; configuración futura no cambia run. list_runs no verifica integridad: deuda visible, no oráculo.",
        "OR-06",
        "IR-10",
        [
            "tests/test_storage_reporting.py::test_db_update_delete_blocked",
            "tests/test_storage_reporting.py::test_tampered_result_detected_after_trigger_bypass",
            "tests/test_storage_reporting.py::test_changed_agreement_preserves_history",
        ],
        fp="Metadata/created_at fuera del hash actual no está autenticada.",
        fn="Rehash malicioso total o truncamiento puede pasar sin copia externa.",
    ),
    family(
        "QA-32",
        "Replay y cambio de artefacto",
        "storage/replay",
        "Resultado nuevo se presenta como reproducción histórica",
        "INV-21 INV-19",
        "RunB; snapshot/ancla; fuente altered; artifact distinto; proceso abierto con código cambiado",
        "1. Replay original. 2. Alterar fuente/snapshot en copia. 3. Cambiar artifact o código cargado. 4. Confirmar que no reescribe resultado.",
        "Mismoartefacto coincide exactamente; integridad fallida/artefacto nuevo/proceso desactualizado rechaza. Reimportación es operación diferente.",
        "OR-06 OR-08",
        "IR-09 IR-10",
        [
            "tests/test_storage_reporting.py::test_save_replay_and_idempotency",
            "tests/test_storage_reporting.py::test_engine_artifact_change_blocks_replay",
            "tests/test_storage_reporting.py::test_source_update_requires_process_restart",
        ],
        fp="Otroartifact rechazado no es nondeterminismo probado.",
        fn="Replay perfecto perpetúa error de importer previo.",
    ),
    family(
        "QA-33",
        "Proveniencia de ejecutables y alcance",
        "metadata/incident tooling",
        "No localizar históricos afectados por importer/reportero",
        "INV-21 INV-28 INV-30",
        "DBhistórica sinimporterhash/client_id; feature configurada no ejecutada; run dañado",
        "1. Ejecutar impact mode=ro con filtrosfeature/importer. 2. Mantener desconocidos en candidatos. 3. Contrastar inventario manual y hashDB antes/después.",
        "Unknown no se excluye; config y trace consultadas; cliente declarado externamente; no escribir schema/triggers ni inventar huellas pasadas.",
        "OR-05 OR-06",
        "IR-09 IR-13",
        ["tests/test_qa_infrastructure.py::test_impact_is_read_only_and_retains_unknowns"],
        status="nuevo",
        fp="Candidato configurado puede no haber ejecutado feature: conservador, no afirmación de daño.",
        fn="Filtrar sólo trace pierde errores previos a calcular.",
    ),
    family(
        "QA-34",
        "Backup, restore y reapertura",
        "SQLite/operations",
        "Backup existe pero no recupera historia/fuentes",
        "INV-25 INV-28",
        "DB2runs/decisiones/fuentes; copia backup a ruta nueva; archivo destino existente",
        "1. Crearbackup conAPI. 2. Restaurar en otra ruta. 3. Verificar inventario/hashes/decisiones/fuentes y replay conartefacto original. 4. Intentar overwrite.",
        "Copia consistente y mismas corridas; overwrite rechazado; original intacto. Copia fuera del equipo exige operación real.",
        "OR-06 OR-10",
        "IR-12",
        ["tests/test_storage_reporting.py::test_migration_reopening_and_consistent_backup"],
        cost="medio",
        human=True,
        fp="Ese test se llama migration pero sólo prueba inicialización/reapertura.",
        fn="Backup sobre mismo disco no cubre pérdida del equipo.",
    ),
    family(
        "QA-35",
        "Crash, rollback y concurrencia",
        "SQLite/exports",
        "Transacción parcial o dos procesos duplican/perdieron historia",
        "INV-25 INV-04",
        "Subproceso copiaDB, fallo antes/despuésINSERT/commit; dosruns simultáneos; disco lleno simulado",
        "1. Inyectar fallo en frontera transaccional. 2. Reabrir copia. 3. Inventariar completos/ausentes y fuentes huérfanas. 4. Validar no corrida parcial visible.",
        "Run completo o ausente, cadena íntegra; busy error recuperable. Fuentes huérfanas pueden existir y no son pérdida histórica; export incompleto no se presenta como completo.",
        "OR-06 OR-10",
        "IR-12",
        ["tests/test_storage_reporting.py::test_decision_chain_serializes_concurrent_writers"],
        cost="alto",
        group="B",
        kind="integration; fault injection",
        effort="1–3 días",
        fp="Proceso terminado no prueba que un commit previo deba desaparecer.",
        fn="Thread test de decisiones no cubre kill de proceso o full disk.",
    ),
    family(
        "QA-36",
        "Schema y migración recuperable",
        "SQLite/version upgrade",
        "Migración interpreta datos previos con semántica nueva",
        "INV-20 INV-25",
        "DBvacía/v1/futurav2; v0no vacía; schema incompleto; futura migración parcial",
        "1. Abrir copias de cadaestado. 2. Futuramigración: backup anclado, ejecutar, fallar enmedio, restore/retry. 3. Comparar históricos y originales.",
        "Vacía inicializa1; futura rechaza; v1reabre sin cambio. v0no vacía/incompleta requiere validación adicional pendiente; ninguna migración real certificada.",
        "OR-06",
        "IR-10 IR-12",
        [
            "tests/test_storage_reporting.py::test_newer_database_schema_is_not_opened",
            "tests/test_storage_reporting.py::test_migration_reopening_and_consistent_backup",
        ],
        group="B",
        cost="alto",
        when="migración; release con cambio de schema",
        effort="1–3 días",
        fp="No inventar downgrade de schema futuro.",
        fn="Una prueba de reopen no cubre atomicidad del DDL.",
    ),
    family(
        "QA-37",
        "Reconciliación entre representaciones",
        "JSON/SQLite/API/XLSX/HTML/UI",
        "Salida cambia estado, importe o identidad",
        "INV-23 INV-03",
        "Run ficticio4estados+monedas;8hojas; exportJSON/HTML; APIrun; observación DOM opcional",
        "1. Verificar run e invariantes. 2. Leer salidas con lectoresindependientes. 3. Comparar filas/monedas/estado/importes y resúmenes. 4. Mutar cada salida y exigir detección.",
        "Camposmateriales exactos; filas completas, sin fórmulas; API/DOM sólo cubiertos si se aportan. Ausencia de canal no es aprobación de ese canal.",
        "OR-03 OR-07",
        "IR-08",
        ["tests/test_qa_infrastructure.py::test_cross_report_reconciliation_and_tamper_detection"],
        status="nuevo",
        cost="medio",
        fp="HTML es resumen: no exigir columna inexistente, sí su contenido declarado.",
        fn="Conciliar salidas iguales no prueba que el core aplicó contrato correcto.",
    ),
    family(
        "QA-38",
        "Límites de reportes y contenido activo",
        "reporting",
        "Truncamiento silencioso o fórmula/HTML se ejecuta",
        "INV-23 INV-25",
        "Texto32768chars, límitefilas reducido en test, nota=HYPERLINK/script, importes36dígitos",
        "1. Exportar. 2. Abrir tiposdecelda/cantidad. 3. Forzar límiteyverificar ZIPsinXLSX+warning+JSONentero. 4. Inspeccionar HTML escapado.",
        "Nunca XLSXparcial; texto explícito sinfórmulas; JSONoriginal íntegro; alerta de omisión conservada.",
        "OR-07 OR-09",
        "IR-08 IR-14",
        [
            "tests/test_storage_reporting.py::test_workbook_is_real_and_has_exact_money_and_no_formulas",
            "tests/test_storage_reporting.py::test_report_escapes_untrusted_html_and_excel_formula",
            "tests/test_storage_reporting.py::test_excel_long_cell_is_not_silently_truncated",
            "tests/test_storage_reporting.py::test_excel_row_limit_preserves_full_bundle_json",
        ],
        kind="integration; security",
        fp="Texto exacto en Excel no es celda numérica sumable automáticamente.",
        fn="Probar límite reducido no mide memoria real de100kfilas.",
    ),
    family(
        "QA-39",
        "UI conserva semántica visible y estado actual",
        "browser/UI",
        "Filtro/cache/formato muestra otra auditoría o dinero alterado",
        "INV-23 INV-24 INV-29",
        "Dosruns parecidos; cantidades1e15+.01como strings;150findings;4estados;decisión distinta",
        "1. Capturar DOM de todaslaspáginas/filtros. 2. Cambiar run rápido, abrir detalle/decidir. 3. Comparar valores visibles y etiquetas conrun exacto. 4. Probar moneda0/3decimales.",
        "No Number/float en dinero; página/filtro no cambia métricasglobales; motor y decisión separados; ningún request fuera de loopback.",
        "OR-07 OR-09",
        "IR-08",
        [],
        status="diseñado",
        cost="medio",
        kind="E2E",
        human=True,
        effort="1–2 días",
        fp="Captura de una página no equivale al lote entero; registrar filtro.",
        fn="API200 no prueba lo que el operador leyó.",
    ),
    family(
        "QA-40",
        "Barrera de red local",
        "server/CLI",
        "Página ajena opera sobre datos locales",
        "INV-26 INV-30",
        "Hostmalicioso,originajeno,tokenfaltante/erróneo,CORSpreflight; socketdelservicio",
        "1. RequestsPOSTsin/contokenyorigin. 2. Verificarbind127.0.0.1enprocesoCLI. 3. Probarlectura cross-origin desde navegador. 4. Inspeccionar efectosDB.",
        "Host/origin/token incorrectos rechazan; sin CORSpermisivo; sólo loopback. 403conefectosprevios es fallo.",
        "OR-09",
        "IR-14",
        ["tests/test_integration.py::test_local_api_security_boundary"],
        kind="security; E2E",
        fp="Token local no autentica usuarios del mismo equipo.",
        fn="TestClient no verifica socketreal/bind ni comportamiento navegador.",
    ),
    family(
        "QA-41",
        "Rutas, archivos y sobrescritura",
        "upload/export/backup",
        "Lectura/escritura fuera del destino permitido",
        "INV-25 INV-30",
        "Canaryoutside;../../name,rutaabsoluta,C:\\name,symlink,destinoexistente",
        "1. Subirfilenamehostil. 2. Exportar/backup a destinos temporales existentes/symlink. 3. Comprobar canary y archivos modificados. 4. Nunca usar archivos reales.",
        "Uploads porhash;no arbitraryread/write; overwrite rechaza. Política efectiva de symlinks queda pendiente antes de confiar rutas compartidas.",
        "OR-09",
        "IR-14",
        [],
        status="diseñado",
        cost="medio",
        kind="security",
        windows=True,
        effort="1–2 días",
        fp="CLI acepta ruta elegida por operador; no confundirla con ruta controlada por upload.",
        fn="Carpeta vacía symlink puede redirigir export sin romper chequeo de nooverwrite.",
    ),
    family(
        "QA-42",
        "XML/ZIP malicioso acotado",
        "XLSX/bundle",
        "Entidades externas, bomb o entrada ambigua supera defensa",
        "INV-25 INV-30",
        "DTDpequeña,entitycanary,ZIPentryduplicate/traversal,archive sizes; process budget",
        "1. Generar archivo pequeño sintético. 2. Ejecutar en subprocess sinredyconlímite. 3. Registrar rechazo/salidas/red/canary. 4. Verificar expansión ademásdeheader.",
        "Sin ejecución/red/lecturaexterna; excepción útilyrecuperable; ninguna corridaeconómica parcial. No instalar archivos activos para la prueba.",
        "OR-09",
        "IR-14",
        ["tests/test_importing.py::test_malformed_xlsx_fuzz_is_bounded_and_classified"],
        cost="medio",
        kind="fuzz; security",
        fp="Rechazo genérico de corrupción es aceptable si no hay efecto y orienta recuperación.",
        fn="Fuzzerdebytes500 no alcanza DTD/zipválido ni expansión.",
    ),
    family(
        "QA-43",
        "Errores de API y consistencia de operación",
        "FastAPI",
        "422/500 oculta escritura parcial o resultado diferente a CLI",
        "INV-25 INV-29",
        "Mappinginválido,campoextra,idajeno,upload32MiB+,mismaentradaCLI/API",
        "1. Registrar inventarioDB. 2. Enviar request inválido. 3. Comparar cambios permitidos de fuentes/configs versus runs. 4. Repetir válido y contrastar resultadoCLI.",
        "Errorrecuperable sinstack al usuario; norunparcial; resultadoeconómicoCLI/APIidéntico; no datos sensibles enrespuesta técnica.",
        "OR-03 OR-07",
        "IR-07 IR-08 IR-12",
        [
            "tests/test_integration.py::test_api_configuration_errors_use_recoverable_messages",
            "tests/test_integration.py::test_api_runs_decisions_export_replay",
            "tests/test_integration.py::test_api_import_with_mapping_and_provenance",
        ],
        severity="HIGH",
        priority="P1",
        fp="Preview conserva fuente/config legítimamente aunque no se ejecuteaudit.",
        fn="Sóloassertstatuscode ignora cuerpo y efectos.",
    ),
    family(
        "QA-44",
        "Auditoría sin servicios externos",
        "core/CLI/UI",
        "Dependencia remota exfiltra o impide auditar",
        "INV-19 INV-30",
        "Fixturesinstalados; socket externo bloqueado; navegador request monitor",
        "1. Bloquear network en core/CLI. 2. Importar,auditar,exportar,replay. 3. NavegarUI conmonitor y comparar destinos.",
        "Audit/exports íntegros offline;UI sólo loopback; instalación inicial de dependencias no se confunde con operaciónoffline.",
        "OR-09",
        "IR-14",
        ["tests/test_integration.py::test_fully_offline_core"],
        severity="HIGH",
        priority="P1",
        kind="integration; E2E",
        fp="Instalaciónrequierepaquetes ya disponibles; no es unallamadaoculta de auditoría.",
        fn="Monkeypatchsocket no detecta subprocesos o navegador externo.",
    ),
    family(
        "QA-45",
        "Representación contractual y mapping aprobados",
        "configuration/operator",
        "Regla válida matemáticamente representa mal el acuerdo",
        "INV-07 INV-08 INV-13",
        "Contrato y ejemplos verdaderos; mínimo porservicio/remito; temporalporcomponente; columnaimporteambigua",
        "1. Aplicarprotocolo pasos1..10. 2. Crear hoja manualantesdelmotor. 3. Confirmar representaciónconcliente. 4. Congelarhashes y dudas.",
        "Toda regla material tiene responsable y ejemplo independiente; desconocido bloquea certeza, no default de industria.",
        "OR-01 OR-04",
        "IR-15",
        [],
        status="diseñado",
        cost="medio",
        kind="manual",
        real=True,
        human=True,
        effort="según contrato; medir horas",
        when="antes de cliente real; cambio contractual",
        fp="Práctica nueva legítima no es bug hasta compararconcontratoconfirmado.",
        fn="Tests sintéticos pueden pasar con contrato equivocado.",
    ),
    family(
        "QA-46",
        "Generalidad de cinco arquetipos",
        "configuration/core",
        "Cliente nuevo requiere excepciones exclusivas",
        "INV-26 INV-13",
        "ArquetiposA..EdeQA_CASES; mismosIDs/preciosdiferentes;Ebasepickup+extradelivery",
        "1. Configurarsincambiarcore. 2. Calcularmanual. 3. Ejecutaryregistrararchivostocados. 4. SiEnocabe fielmente,documentarabstracciónfaltante.",
        "A31.5,B900,Cbandas/pallet/evidencia,D194.25USD, E100+12 separado sólo si fiel al contrato. Sinif cliente/sector/carrier encore.",
        "OR-01 OR-05",
        "IR-15 IR-13",
        ["tests/test_integration.py::test_real_files_three_agreements_golden_and_second_client"],
        severity="HIGH",
        priority="P1",
        cost="medio",
        human=True,
        fp="Cambio reutilizable justificado delcore no equivale a custom.",
        fn="QuintoarquetipoE no está ejercitadoporeltest existente.",
    ),
    family(
        "QA-47",
        "Paquete y plataforma real",
        "packaging/OS",
        "Checkoutfunciona pero instalación pierde archivos o cambia importación",
        "INV-21 INV-23",
        "Wheel/sdist recién construidos; directorioajenoalrepo; Linux y Windows de uso",
        "1. Instalarpaqueteaislado. 2. SmokeconUIstatic/demo/replay/export. 3. Compararcontenidos/hash. 4. Windows: rutasUnicode,longitudes,lineendings,Excel real.",
        "Importdesdepaqueteinstalado,noeditable; recursoscompletos; equivalenciaeconómica. Windowsnoaprobadosinmáquinareal.",
        "OR-04 OR-06 OR-07",
        "IR-07 IR-08",
        [],
        status="diseñado",
        severity="HIGH",
        priority="P1",
        group="B",
        cost="alto",
        windows=True,
        effort="1–2 días",
        when="release; antes de cliente real",
        fp="FechasZIPybuildhashpuedencambiar sin cambioeconómico; comparararchivos materialmente.",
        fn="LinuxCI no valida Windows ni aplicaciónExcel.",
    ),
    family(
        "QA-48",
        "Escala, memoria y tiempos de todas las etapas",
        "performance",
        "Cierre real excedeRAM o timeout y salida parece completa",
        "INV-25",
        "10kS/50kC y100kC; trazascompletas;tabla10ktarifas;mediciónporfase",
        "1. Unproceso/tamañoconRSSbaseline. 2. Medirimport/audit/hash/save/export/UIporseparado. 3. Conciliarcantidadesysumasalterminar.",
        "Sinpérdida/resultadoequivocado;presupuestooperativoacordado. Baselinescore15.953s/945.9MiB y31.577s/1821.2MiB no sonSLAend-to-end.",
        "OR-03 OR-10",
        "IR-12",
        [],
        status="diseñado",
        severity="HIGH",
        priority="P2",
        group="B",
        cost="alto",
        kind="benchmark",
        effort="1–3 días",
        when="cambio algorítmico; volumen nuevo; release relevante",
        fp="Ruido de carga/maquinadistinta no es regresión causal.",
        fn="Benchmarksinpersistencia/reportes oculta pico real delcierre.",
    ),
    family(
        "QA-49",
        "Los verificadores detectan corrupción",
        "QA/oracles",
        "Checker pasa todo o importa lógica defectuosa del motor",
        "INV-01 INV-04 INV-23",
        "Runválido y copias conconfirmedfake,IDduplicado,sumamutada,labelFAILenXLSX,missingrow",
        "1. Esperarchecklimpiodebaseline. 2. Modificarunacausa por copia. 3. Exigirmensajeidentificableyexit1. 4. Inputmalformadoexit2.",
        "Cada manipulaciónobjetivorechazada;nocoreimportsenqa/referenceorinvariants;pendientesclaros,noformatoPythonassertcomoúnicobarreraCLI.",
        "OR-01 OR-03 OR-07",
        "IR-08 IR-06",
        [
            "tests/test_qa_infrastructure.py::test_checker_rejects_economic_corruption",
            "tests/test_qa_infrastructure.py::test_cross_report_reconciliation_and_tamper_detection",
        ],
        status="nuevo",
        kind="mutation; unit",
        fp="Corregircapturaincompletaantesdeatribuirfallaalproducto.",
        fn="Sólo probarqueunbuenrunpasa no pruebaqueelchecker sirva.",
    ),
    family(
        "QA-50",
        "Mutantes críticos dirigidos",
        "mutation infrastructure",
        "Tests verdes no detectan eliminación de defensas",
        "INV-01 INV-02 INV-06 INV-07 INV-09",
        "qa/mutants.json, copias temporales src/tests/fixtures; baseline sano",
        "1. Validaranclaúnica. 2. Ejecutarbaselineenlacopia. 3. Aplicarunmutante. 4. Ejecutarsusselectores. 5. Requerirfailuredeassert,no collectionerror/timeout.",
        "Mutacionesdesigno,tolerancia,moneda,versiónyevidencia mueren porassert causal; sobreviviente bloqueafeature;incompetente/inconclusivo no cuenta muerto.",
        "OR-01 OR-05",
        "IR-06 IR-03",
        [],
        status="nuevo",
        cost="medio",
        kind="mutation",
        effort="2–4 h por mutante nuevo",
        when="cambio de defensa; release; después de incidente",
        fp="CambiosdeAPIoanclahacenmutanteobsoleto,noequivalente.",
        fn="Fallodehashglobalmata mutante sin ejercitar invariante; revisar causalidad.",
    ),
    family(
        "QA-51",
        "Validación ciega con cliente",
        "field validation",
        "Confundir coincidencia sintética con seguridad económica real",
        "INV-12 INV-13 INV-22",
        "Períodoverdaderoycontrolhistóricoconcustodioseparado;REAL_CLIENT_VALIDATION_PROTOCOL",
        "1. Congelarrepresentaciónycorridaantesdevercontrol. 2. Compararporcargo/moneda. 3. RevisarfalsosPASS/FAILyconocidas/nuevas/desconocidas. 4. Registrarhoras.",
        "Verdadcontrasteexterna; nueva correctanoequivalearecupero; no ajustarprimera corrida trasverrespuestas sin conservarla.",
        "OR-01 OR-04",
        "IR-15 IR-01 IR-02",
        [],
        status="diseñado",
        cost="alto",
        group="B",
        kind="manual",
        real=True,
        human=True,
        effort="según período; medir",
        when="antes de cliente real; nuevo arquetipo",
        fp="Diferentealcance/períodonopermitecompararmontosdirectamente.",
        fn="Controlhistórico también puedeestar equivocado; requerir resoluciónindependiente.",
    ),
    family(
        "QA-52",
        "Gate de pago sin nuestra supervisión",
        "release/use policy",
        "Habilitaruso sensible por cantidad de tests verdes",
        "INV-01 INV-21 INV-25 INV-26",
        "GateUdeRELEASE_CRITERIA; evidencias reales/operativas/Windows según alcance",
        "1. EvaluarcadaobligaciónGateU. 2. Anotarpendientes/incidentes/desconocidos. 3. Exigirrestriccionesefectivas/restore/identidad/totaldocumental.",
        "GateUcerradoen0.1.0; ninguna estadística sintética lo abre; no sustituiraprobacióncontractualconpytest.",
        "OR-01 OR-06 OR-10",
        "IR-15",
        [],
        status="diseñado",
        group="B",
        cost="alto",
        kind="manual",
        real=True,
        human=True,
        effort="no estimable sin piloto",
        when="antes de habilitar decisiones sin supervisión",
        fp="Noexigirestegateparadesarrolloofflineconficticios.",
        fn="Confundirpilotoconsupervisión con aprobaciónautónoma.",
    ),
    family(
        "QA-53",
        "IDs y JSON inequívocos",
        "serialization/models",
        "Clave duplicada o IDcolisionado cambia interpretación",
        "INV-04 INV-26",
        "JSONconamount1 y100repetidos;S/C/A/EIDsduplicados;datosmalformados/unknownfield",
        "1. LeerJSONconparserproducto. 2. Validarduplicadosporentidad. 3. Verificarrechazosimportvisibles. 4. ProbarcheckerJSONestricto.",
        "Clavesrepetidas/nonfinite/extra fields rechazados; ninguna filaúltimagana silenciosamente;duplicados deimportsevisibilizan.",
        "OR-04",
        "IR-07 IR-13",
        [
            "tests/test_adversarial.py::test_duplicate_json_keys_are_rejected",
            "tests/test_importing.py::test_duplicate_business_ids_visible_not_silently_deduplicated",
        ],
        kind="fuzz; unit",
        fp="MismoIDentreentidades diferentes puede ser válido; espacio deIDs es porentidad.",
        fn="ParserdeherramientaQA permisivopuedeaceptarloqueproductorechaza.",
    ),
    family(
        "QA-54",
        "Bundle portable y ancla externa",
        "archive/integrity",
        "Paquete alterado parece evidencia confiable",
        "INV-21 INV-22 INV-28",
        "ZIPdemo;mutararchivo/manifest/snapshot/decisión;duplicateentries/fuentefaltante/pathhostil",
        "1. Verificarmanifestmásrunmáschainmásfuentes. 2. CompararhashZIPconanclaexterna. 3. Mutaruncomponente. 4. NoextraerZIPajeno para verificar.",
        "Cadaalteración detectadarelativaancla;manifestautoconsistente no pruebaautenticidad;metadatafueradehash se informa.",
        "OR-06 OR-09",
        "IR-10 IR-14",
        ["tests/test_storage_reporting.py::test_portable_bundle_integrity"],
        kind="security; integration",
        fp="ZIPlegítimoreexportado puedecambiartimestamps/hash decontenedor.",
        fn="Atacantepuederehacertodosloshashes;sinanclano hay autenticación.",
    ),
    family(
        "QA-55",
        "Entrega reproducible y dependencias",
        "Git/build/environment",
        "Tests locales prueban archivos distintos de los entregados",
        "INV-21 INV-19",
        "Commitlimpio;checkoutaislado;lock;originalesconCRLFySHA;wheel/sdist",
        "1. Compararárbolversionado/materiales. 2. Instalaryprobarencheckoutlimpio. 3. Registrarhuellasdelpaquete/deps. 4. VerificarsemánticaconLFsinexigirSHAdeloriginalCRLF.",
        "Códigoentregado coincideconverificado;datosoriginales mantienenhashpropiodesusbytes;sinsecrets/DB/outputenGit. No asumir buildsbit-identicalsinsello reproducible.",
        "OR-06 OR-08",
        "IR-09 IR-07",
        [],
        status="diseñado",
        severity="HIGH",
        priority="P1",
        group="B",
        cost="medio",
        effort="4–8 h",
        when="release; cambio de dependencias",
        fp="Normalizarnewline cambiabytes/provenance pero noeconomía si parsingesigual.",
        fn="Editableinstall puedeocultar recurso faltante enwheel.",
    ),
    family(
        "QA-56",
        "Separación de liquidaciones y alcance de obligación",
        "grouping/domain",
        "Sumar cargos de servicios/períodos distintos por clave incompleta",
        "INV-05 INV-09 INV-13",
        "SrefR;C100L1yC100L2;base100;clientedefine2serviciosindependientes",
        "1. Revisargroup_keyycontrato. 2. Ejecutarsinperiodoenclave. 3. Configurarperíodo/servicioexplícito conoperacionescorrectas. 4. Comparargrafoobligaciones.",
        "Dosobligacionesindependientesno se comparancontrau nE100. Elcoreactualnoincluyesettlementenagrupación: mapping/scope confirmadosodeclararcaso no soportado.",
        "OR-01 OR-05",
        "IR-04 IR-15",
        [],
        status="diseñado",
        human=True,
        cost="medio",
        effort="4–8 h",
        when="nuevo formato; cambio de matching; antes de cliente real",
        fp="Doslíneasdefacturaspuedencompletarunservicio;noasumirsiempreindependientes.",
        fn="Fixturesdeunúnicoperíodonoejercitanesteerrorcausal.",
    ),
    family(
        "QA-57",
        "Diagnóstico no muta evidencia",
        "QA/forensics",
        "Herramienta deincidente inicializa/migraDB original",
        "INV-30 INV-28",
        "DBreadonly, schemafuturo/incompleto, filaJSONcorrupta; hashesprevios",
        "1. Ejecutarimpactenmode=ro. 2. Intentarinputinexistente. 3. Compararbytes/schema/triggersantesdespués. 4. Corruptoapareceunknown o errorglobal explícito.",
        "NoStoreconstructor,nocreaciónDB/nuevostriggers; ninguna selección vacía falsa por corrupción.",
        "OR-06 OR-09",
        "IR-12 IR-14",
        ["tests/test_qa_infrastructure.py::test_impact_is_read_only_and_retains_unknowns"],
        status="nuevo",
        fp="UnDBactivo puede cambiar porprocesoproductivo;congelarcopia para compararhash.",
        fn="Chequearsolomtime no demuestraausenciademutación.",
    ),
    family(
        "QA-58",
        "Píxel exacto y matrices visuales exhaustivas",
        "cosmetic UI",
        "Desviación estética sin impacto enlectura",
        "INV-23 (sólo si cambia significado)",
        "TodaslascombinacionesdeSO/fuentes/anchos, sin defectoseconómicos conocidos",
        "1. Diferirpixelperfect. 2. Conservar sólo prueba de texto/contraste/overflow material enQA39. 3. Reconsiderar ante fallo real de lectura.",
        "No gastarbudgetenmatrizestéticaexhaustiva; cualquierimporte/labeloculto escala aQA39/P0.",
        "OR-07",
        "IR-08",
        [],
        severity="LOW",
        priority="P3",
        group="C",
        cost="alto",
        status="diferido",
        kind="E2E",
        likelihood=2,
        detection=1,
        effort="diferido",
        when="sólo si aparece necesidad material",
        fp="Antialiasing/fuenteproduce diffsinerroroperativo.",
        fn="Descartardiseñovisualnoautorizaocultar moneda/estado.",
    ),
]
